-- M0006: organizacoes conforme baseline H2C.3E

CREATE TABLE associacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'EM_IMPLANTACAO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    inativado_em TIMESTAMPTZ
);

CREATE TABLE associacao_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    alias TEXT NOT NULL,
    alias_normalizado TEXT NOT NULL,
    origem TEXT NOT NULL,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE associacao_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE uvrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'EM_IMPLANTACAO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    responsavel_usuario_id INTEGER,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    inativado_em TIMESTAMPTZ
);

CREATE TABLE uvr_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uvr_id BIGINT NOT NULL,
    alias TEXT NOT NULL,
    alias_normalizado TEXT NOT NULL,
    origem TEXT NOT NULL,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE uvr_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uvr_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

ALTER TABLE associacoes
    ADD CONSTRAINT pk_associacoes PRIMARY KEY (id);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT pk_assoc_aliases PRIMARY KEY (id);

ALTER TABLE associacao_eventos
    ADD CONSTRAINT pk_assoc_eventos PRIMARY KEY (id);

ALTER TABLE uvrs
    ADD CONSTRAINT pk_uvrs PRIMARY KEY (id);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT pk_uvr_aliases PRIMARY KEY (id);

ALTER TABLE uvr_eventos
    ADD CONSTRAINT pk_uvr_eventos PRIMARY KEY (id);

ALTER TABLE associacoes
    ADD CONSTRAINT uq_associacoes__codigo UNIQUE (codigo);

ALTER TABLE associacoes
    ADD CONSTRAINT uq_associacoes__nome_normalizado UNIQUE (nome_normalizado);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT uq_assoc_aliases__alias_normalizado UNIQUE (alias_normalizado);

ALTER TABLE uvrs
    ADD CONSTRAINT uq_uvrs__codigo UNIQUE (codigo);

ALTER TABLE uvrs
    ADD CONSTRAINT uq_uvrs__assoc_id_nome_normalizado UNIQUE (associacao_id, nome_normalizado);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT uq_uvr_aliases__alias_normalizado UNIQUE (alias_normalizado);

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__estado CHECK (estado IN ('EM_IMPLANTACAO', 'ATIVA', 'INATIVA'));

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__alias_preenchido CHECK (btrim(alias) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__alias_normalizado_preenchido CHECK (btrim(alias_normalizado) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associacao_eventos
    ADD CONSTRAINT ck_assoc_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE associacao_eventos
    ADD CONSTRAINT ck_assoc_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__estado CHECK (estado IN ('EM_IMPLANTACAO', 'ATIVA', 'INATIVA'));

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__alias_preenchido CHECK (btrim(alias) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__alias_normalizado_preenchido CHECK (btrim(alias_normalizado) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE uvr_eventos
    ADD CONSTRAINT ck_uvr_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE uvr_eventos
    ADD CONSTRAINT ck_uvr_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT fk_assoc_aliases__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_aliases
    ADD CONSTRAINT fk_assoc_aliases__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_eventos
    ADD CONSTRAINT fk_assoc_eventos__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_eventos
    ADD CONSTRAINT fk_assoc_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacoes
    ADD CONSTRAINT fk_associacoes__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacoes
    ADD CONSTRAINT fk_associacoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_aliases
    ADD CONSTRAINT fk_uvr_aliases__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_aliases
    ADD CONSTRAINT fk_uvr_aliases__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_eventos
    ADD CONSTRAINT fk_uvr_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_eventos
    ADD CONSTRAINT fk_uvr_eventos__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__responsavel_usr_id FOREIGN KEY (responsavel_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_assoc_aliases__assoc_id
    ON associacao_aliases (associacao_id);

CREATE INDEX ix_assoc_aliases__criado_por_usr_id
    ON associacao_aliases (criado_por_usuario_id);

CREATE INDEX ix_assoc_eventos__assoc_id
    ON associacao_eventos (associacao_id);

CREATE INDEX ix_assoc_eventos__criado_por_usr_id
    ON associacao_eventos (criado_por_usuario_id);

CREATE INDEX ix_associacoes__atualizado_por_usr_id
    ON associacoes (atualizado_por_usuario_id);

CREATE INDEX ix_associacoes__criado_por_usr_id
    ON associacoes (criado_por_usuario_id);

CREATE INDEX ix_uvr_aliases__criado_por_usr_id
    ON uvr_aliases (criado_por_usuario_id);

CREATE INDEX ix_uvr_aliases__uvr_id
    ON uvr_aliases (uvr_id);

CREATE INDEX ix_uvr_eventos__criado_por_usr_id
    ON uvr_eventos (criado_por_usuario_id);

CREATE INDEX ix_uvr_eventos__uvr_id
    ON uvr_eventos (uvr_id);

CREATE INDEX ix_uvrs__atualizado_por_usr_id
    ON uvrs (atualizado_por_usuario_id);

CREATE INDEX ix_uvrs__criado_por_usr_id
    ON uvrs (criado_por_usuario_id);

CREATE INDEX ix_uvrs__responsavel_usr_id
    ON uvrs (responsavel_usuario_id);

CREATE INDEX ix_associacoes__estado_nome_normalizado
    ON associacoes (estado, nome_normalizado);

CREATE INDEX ix_uvrs__assoc_id_estado_nome_normalizado
    ON uvrs (associacao_id, estado, nome_normalizado);
