-- M0007: escopos conforme baseline H2C.3E

CREATE TABLE auth_escopos_globais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE auth_escopos_associacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE auth_escopos_uvr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT pk_auth_escopos_globais PRIMARY KEY (id);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT pk_auth_escopos_associacao PRIMARY KEY (id);

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT pk_auth_escopos_uvr PRIMARY KEY (id);

CREATE UNIQUE INDEX uq_auth_escopos_globais__usr_perfil_id
    ON auth_escopos_globais (usuario_perfil_id)
    WHERE fim_em IS NULL;

CREATE UNIQUE INDEX uq_auth_escopos_assoc__usr_perfil_id_assoc_id
    ON auth_escopos_associacao (usuario_perfil_id, associacao_id)
    WHERE fim_em IS NULL;

CREATE UNIQUE INDEX uq_auth_escopos_uvr__usr_perfil_id_uvr_id
    ON auth_escopos_uvr (usuario_perfil_id, uvr_id)
    WHERE fim_em IS NULL;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT ck_auth_escopos_globais__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT ck_auth_escopos_assoc__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT ck_auth_escopos_uvr__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT fk_auth_escopos_globais__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT fk_auth_escopos_globais__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_auth_escopos_assoc__assoc_id
    ON auth_escopos_associacao (associacao_id);

CREATE INDEX ix_auth_escopos_assoc__criado_por_usr_id
    ON auth_escopos_associacao (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_globais__criado_por_usr_id
    ON auth_escopos_globais (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_uvr__criado_por_usr_id
    ON auth_escopos_uvr (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_uvr__uvr_id
    ON auth_escopos_uvr (uvr_id);
