-- M0009: associados conforme baseline H2C.3E

CREATE TABLE associados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    cpf VARCHAR(11),
    documento_alternativo TEXT,
    justificativa_sem_cpf TEXT,
    data_nascimento DATE,
    email TEXT,
    telefone TEXT,
    cep VARCHAR(8),
    logradouro TEXT,
    endereco_numero TEXT,
    bairro TEXT,
    cidade TEXT,
    uf CHAR(2),
    estado TEXT NOT NULL DEFAULT 'RASCUNHO',
    condicao_regularizacao TEXT,
    data_admissao DATE,
    data_desligamento DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE associado_associacao_vinculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associado_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    tipo_vinculo TEXT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    estado TEXT NOT NULL DEFAULT 'PENDENTE',
    motivo TEXT,
    solicitado_por_usuario_id INTEGER NOT NULL,
    aprovado_por_usuario_id INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL
);

CREATE TABLE associado_uvr_vinculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associado_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    tipo_vinculo TEXT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    estado TEXT NOT NULL DEFAULT 'PENDENTE',
    motivo TEXT,
    solicitado_por_usuario_id INTEGER NOT NULL,
    aprovado_por_usuario_id INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL
);

CREATE TABLE associado_contas_bancarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associado_id BIGINT NOT NULL,
    finalidade TEXT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    instituicao_codigo TEXT NOT NULL,
    instituicao_nome TEXT NOT NULL,
    agencia TEXT NOT NULL,
    agencia_digito TEXT,
    conta TEXT NOT NULL,
    conta_digito TEXT,
    tipo_conta TEXT NOT NULL,
    chave_pix TEXT,
    tipo_chave_pix TEXT,
    titular_nome TEXT NOT NULL,
    titular_documento TEXT,
    estado TEXT NOT NULL DEFAULT 'PENDENTE',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    inativado_em TIMESTAMPTZ
);

CREATE TABLE associado_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associado_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL
);

CREATE TABLE associado_conta_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conta_bancaria_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    categoria TEXT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

ALTER TABLE associados
    ADD CONSTRAINT pk_associados PRIMARY KEY (id);

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT pk_associado_assoc_vinculos PRIMARY KEY (id);

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT pk_associado_uvr_vinculos PRIMARY KEY (id);

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT pk_associado_contas_bancarias PRIMARY KEY (id);

ALTER TABLE associado_eventos
    ADD CONSTRAINT pk_associado_eventos PRIMARY KEY (id);

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT pk_associado_conta_documentos PRIMARY KEY (id);

ALTER TABLE associados
    ADD CONSTRAINT uq_associados__numero UNIQUE (numero);

CREATE UNIQUE INDEX uq_associados__cpf
    ON associados (cpf)
    WHERE cpf IS NOT NULL;

CREATE UNIQUE INDEX uq_associado_assoc_vinculos__associado_id
    ON associado_associacao_vinculos (associado_id)
    WHERE principal = TRUE AND estado = 'ATIVO' AND fim_data IS NULL;

CREATE UNIQUE INDEX uq_associado_uvr_vinculos__associado_id
    ON associado_uvr_vinculos (associado_id)
    WHERE principal = TRUE AND estado = 'ATIVO' AND fim_data IS NULL;

CREATE UNIQUE INDEX uq_associado_contas_bancarias__associado_id_finalidade
    ON associado_contas_bancarias (associado_id, finalidade)
    WHERE principal = TRUE AND estado = 'ATIVA' AND fim_data IS NULL;

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__numero_preenchido CHECK (btrim(numero) <> '');

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__estado CHECK (estado IN ('RASCUNHO', 'ATIVO', 'INATIVO', 'DESLIGADO'));

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT ck_associado_assoc_vinculos__tipo_vinculo_preenchido CHECK (btrim(tipo_vinculo) <> '');

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT ck_associado_assoc_vinculos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT ck_associado_assoc_vinculos__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT ck_associado_assoc_vinculos__estado CHECK (estado IN ('PENDENTE', 'ATIVO', 'ENCERRADO', 'REJEITADO'));

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT ck_associado_assoc_vinculos__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT ck_associado_uvr_vinculos__tipo_vinculo_preenchido CHECK (btrim(tipo_vinculo) <> '');

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT ck_associado_uvr_vinculos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT ck_associado_uvr_vinculos__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT ck_associado_uvr_vinculos__estado CHECK (estado IN ('PENDENTE', 'ATIVO', 'ENCERRADO', 'REJEITADO'));

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT ck_associado_uvr_vinculos__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__finalidade_preenchido CHECK (btrim(finalidade) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__instituicao_codigo_preenchido CHECK (btrim(instituicao_codigo) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__instituicao_nome_preenchido CHECK (btrim(instituicao_nome) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__agencia_preenchido CHECK (btrim(agencia) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__conta_preenchido CHECK (btrim(conta) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__tipo_conta_preenchido CHECK (btrim(tipo_conta) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__titular_nome_preenchido CHECK (btrim(titular_nome) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__estado CHECK (estado IN ('PENDENTE', 'ATIVA', 'INATIVA'));

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT ck_associado_contas_bancarias__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associado_eventos
    ADD CONSTRAINT ck_associado_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE associado_eventos
    ADD CONSTRAINT ck_associado_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE associado_eventos
    ADD CONSTRAINT ck_associado_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT ck_associado_conta_documentos__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT ck_associado_conta_documentos__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE associados
    ADD CONSTRAINT ck_associados__regra_265 CHECK ((cpf IS NOT NULL AND cpf ~ '^[0-9]{11}$' AND justificativa_sem_cpf IS NULL) OR (cpf IS NULL AND btrim(coalesce(justificativa_sem_cpf,'')) <> ''));

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT fk_associado_assoc_vinculos__aprovado_por_usr_id FOREIGN KEY (aprovado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT fk_associado_assoc_vinculos__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT fk_associado_assoc_vinculos__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_associacao_vinculos
    ADD CONSTRAINT fk_associado_assoc_vinculos__solicitado_por_usr_id FOREIGN KEY (solicitado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT fk_associado_conta_documentos__conta_bancaria_id FOREIGN KEY (conta_bancaria_id)
    REFERENCES associado_contas_bancarias (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT fk_associado_conta_documentos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_conta_documentos
    ADD CONSTRAINT fk_associado_conta_documentos__documento_id FOREIGN KEY (documento_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT fk_associado_contas_bancarias__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT fk_associado_contas_bancarias__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_contas_bancarias
    ADD CONSTRAINT fk_associado_contas_bancarias__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_eventos
    ADD CONSTRAINT fk_associado_eventos__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_eventos
    ADD CONSTRAINT fk_associado_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT fk_associado_uvr_vinculos__aprovado_por_usr_id FOREIGN KEY (aprovado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT fk_associado_uvr_vinculos__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT fk_associado_uvr_vinculos__solicitado_por_usr_id FOREIGN KEY (solicitado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associado_uvr_vinculos
    ADD CONSTRAINT fk_associado_uvr_vinculos__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associados
    ADD CONSTRAINT fk_associados__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associados
    ADD CONSTRAINT fk_associados__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_associado_assoc_vinculos__aprovado_por_usr_id
    ON associado_associacao_vinculos (aprovado_por_usuario_id);

CREATE INDEX ix_associado_assoc_vinculos__assoc_id
    ON associado_associacao_vinculos (associacao_id);

CREATE INDEX ix_associado_assoc_vinculos__solicitado_por_usr_id
    ON associado_associacao_vinculos (solicitado_por_usuario_id);

CREATE INDEX ix_associado_conta_documentos__conta_bancaria_id
    ON associado_conta_documentos (conta_bancaria_id);

CREATE INDEX ix_associado_conta_documentos__criado_por_usr_id
    ON associado_conta_documentos (criado_por_usuario_id);

CREATE INDEX ix_associado_conta_documentos__documento_id
    ON associado_conta_documentos (documento_id);

CREATE INDEX ix_associado_contas_bancarias__atualizado_por_usr_id
    ON associado_contas_bancarias (atualizado_por_usuario_id);

CREATE INDEX ix_associado_contas_bancarias__criado_por_usr_id
    ON associado_contas_bancarias (criado_por_usuario_id);

CREATE INDEX ix_associado_eventos__associado_id
    ON associado_eventos (associado_id);

CREATE INDEX ix_associado_eventos__criado_por_usr_id
    ON associado_eventos (criado_por_usuario_id);

CREATE INDEX ix_associado_uvr_vinculos__aprovado_por_usr_id
    ON associado_uvr_vinculos (aprovado_por_usuario_id);

CREATE INDEX ix_associado_uvr_vinculos__solicitado_por_usr_id
    ON associado_uvr_vinculos (solicitado_por_usuario_id);

CREATE INDEX ix_associado_uvr_vinculos__uvr_id
    ON associado_uvr_vinculos (uvr_id);

CREATE INDEX ix_associados__atualizado_por_usr_id
    ON associados (atualizado_por_usuario_id);

CREATE INDEX ix_associados__criado_por_usr_id
    ON associados (criado_por_usuario_id);

CREATE INDEX ix_associados__estado_nome_normalizado
    ON associados (estado, nome_normalizado);
