-- M0005: auditoria conforme baseline H2C.3E

CREATE TABLE auditoria_tecnica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id UUID NOT NULL,
    modulo TEXT NOT NULL,
    acao TEXT NOT NULL,
    resultado TEXT NOT NULL,
    tipo_ator TEXT NOT NULL,
    usuario_id INTEGER,
    identificador_ator_tecnico TEXT,
    objeto_tipo TEXT,
    objeto_identificador TEXT,
    associacao_id BIGINT,
    uvr_id BIGINT,
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip INET,
    agente_resumido TEXT,
    origem TEXT NOT NULL,
    justificativa TEXT,
    estado_anterior JSONB,
    estado_posterior JSONB,
    metadados JSONB,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    erro_codigo TEXT
);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT pk_auditoria_tecnica PRIMARY KEY (id);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__modulo_preenchido CHECK (btrim(modulo) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__acao_preenchido CHECK (btrim(acao) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__tipo_ator_preenchido CHECK (btrim(tipo_ator) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__regra_274 CHECK ((estado_anterior IS NULL OR (jsonb_typeof(estado_anterior)='object' AND octet_length(estado_anterior::text)<=65536)) AND (estado_posterior IS NULL OR (jsonb_typeof(estado_posterior)='object' AND octet_length(estado_posterior::text)<=65536)) AND (metadados IS NULL OR (jsonb_typeof(metadados)='object' AND octet_length(metadados::text)<=65536)));

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__usr_id FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_auditoria_tecnica__assoc_id
    ON auditoria_tecnica (associacao_id);

CREATE INDEX ix_auditoria_tecnica__usr_id
    ON auditoria_tecnica (usuario_id);

CREATE INDEX ix_auditoria_tecnica__uvr_id
    ON auditoria_tecnica (uvr_id);

CREATE INDEX ix_auditoria_tecnica__request_id
    ON auditoria_tecnica (request_id);

CREATE INDEX ix_auditoria_tecnica__objeto_tipo_objeto_identificad_b1794c8b
    ON auditoria_tecnica (objeto_tipo, objeto_identificador, ocorrido_em);

CREATE INDEX ix_auditoria_tecnica__tipo_ator_usr_id_ocorrido_em
    ON auditoria_tecnica (tipo_ator, usuario_id, ocorrido_em);
