-- M0003: usuarios conforme baseline H2C.3E

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username TEXT NOT NULL,
    username_normalizado TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    nome_completo TEXT NOT NULL,
    email TEXT,
    email_normalizado TEXT,
    estado TEXT NOT NULL DEFAULT 'PENDENTE',
    exige_troca_senha BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    criado_por_usuario_id INTEGER,
    inativado_em TIMESTAMPTZ,
    inativado_por_usuario_id INTEGER
);

CREATE TABLE usuario_recuperacoes_senha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id INTEGER NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em TIMESTAMPTZ NOT NULL,
    usado_em TIMESTAMPTZ,
    invalidado_em TIMESTAMPTZ,
    motivo_invalidacao TEXT,
    request_id UUID NOT NULL,
    ip INET,
    agente_resumido TEXT,
    criado_por_tipo_ator TEXT NOT NULL,
    invalidado_por_usuario_id INTEGER
);

ALTER TABLE usuarios
    ADD CONSTRAINT pk_usuarios PRIMARY KEY (id);

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT pk_usr_recuperacoes_senha PRIMARY KEY (id);

ALTER TABLE usuarios
    ADD CONSTRAINT uq_usuarios__username_normalizado UNIQUE (username_normalizado);

CREATE UNIQUE INDEX uq_usuarios__email_normalizado
    ON usuarios (email_normalizado)
    WHERE email_normalizado IS NOT NULL;

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT uq_usr_recuperacoes_senha__token_hash UNIQUE (token_hash);

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__username_preenchido CHECK (btrim(username) <> '');

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__username_normalizado_preenchido CHECK (btrim(username_normalizado) <> '');

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__nome_completo_preenchido CHECK (btrim(nome_completo) <> '');

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__estado CHECK (estado IN ('ATIVO', 'INATIVO', 'BLOQUEADO', 'PENDENTE'));

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT ck_usr_recuperacoes_senha__criado_por_tipo_ator_preenchido CHECK (btrim(criado_por_tipo_ator) <> '');

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios__regra_263 CHECK (username_normalizado = lower(btrim(username_normalizado)) AND username_normalizado !~ '[[:space:]]' AND username_normalizado <> '');

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT ck_usr_recuperacoes_senha__regra_264 CHECK (expira_em > criado_em AND (usado_em IS NULL OR usado_em >= criado_em) AND (invalidado_em IS NULL OR invalidado_em >= criado_em));

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT fk_usr_recuperacoes_senha__invalidado_por_usr_id FOREIGN KEY (invalidado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE usuario_recuperacoes_senha
    ADD CONSTRAINT fk_usr_recuperacoes_senha__usr_id FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios__inativado_por_usr_id FOREIGN KEY (inativado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_usr_recuperacoes_senha__invalidado_por_usr_id
    ON usuario_recuperacoes_senha (invalidado_por_usuario_id);

CREATE INDEX ix_usr_recuperacoes_senha__usr_id
    ON usuario_recuperacoes_senha (usuario_id);

CREATE INDEX ix_usuarios__criado_por_usr_id
    ON usuarios (criado_por_usuario_id);

CREATE INDEX ix_usuarios__inativado_por_usr_id
    ON usuarios (inativado_por_usuario_id);

CREATE INDEX ix_usuarios__estado_username_normalizado
    ON usuarios (estado, username_normalizado);

CREATE INDEX ix_usr_recuperacoes_senha__usr_id_expira_em
    ON usuario_recuperacoes_senha (usuario_id, expira_em);
