-- M0008: documentos conforme baseline H2C.3E

CREATE TABLE documentos_privados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    provedor TEXT NOT NULL,
    chave_provedor TEXT NOT NULL,
    nome_original TEXT NOT NULL,
    nome_seguro TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    extensao TEXT NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    versao INTEGER NOT NULL DEFAULT 1,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    privacidade TEXT NOT NULL,
    substituido_por_id BIGINT,
    retencao_ate DATE,
    excluido_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

ALTER TABLE documentos_privados
    ADD CONSTRAINT pk_documentos_privados PRIMARY KEY (id);

ALTER TABLE documentos_privados
    ADD CONSTRAINT uq_documentos_privados__identificador_publico UNIQUE (identificador_publico);

ALTER TABLE documentos_privados
    ADD CONSTRAINT uq_documentos_privados__chave_provedor UNIQUE (chave_provedor);

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__provedor_preenchido CHECK (btrim(provedor) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__chave_provedor_preenchido CHECK (btrim(chave_provedor) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__nome_original_preenchido CHECK (btrim(nome_original) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__nome_seguro_preenchido CHECK (btrim(nome_seguro) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__mime_type_preenchido CHECK (btrim(mime_type) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__extensao_preenchido CHECK (btrim(extensao) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__versao_positivo CHECK (versao > 0);

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__privacidade_preenchido CHECK (btrim(privacidade) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__estado CHECK (estado IN ('ATIVO', 'SUBSTITUIDO', 'INATIVO', 'EXCLUSAO_PENDENTE'));

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__regra_268 CHECK (sha256 ~ '^[0-9a-f]{64}$' AND tamanho_bytes >= 0 AND versao > 0);

ALTER TABLE documentos_privados
    ADD CONSTRAINT fk_documentos_privados__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE documentos_privados
    ADD CONSTRAINT fk_documentos_privados__substituido_por_id FOREIGN KEY (substituido_por_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_documentos_privados__criado_por_usr_id
    ON documentos_privados (criado_por_usuario_id);

CREATE INDEX ix_documentos_privados__substituido_por_id
    ON documentos_privados (substituido_por_id);

CREATE INDEX ix_documentos_privados__estado_retencao_ate
    ON documentos_privados (estado, retencao_ate);

CREATE INDEX ix_documentos_privados__sha256
    ON documentos_privados (sha256);
