CREATE TABLE public.schema_migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    migration_id TEXT NOT NULL,
    modulo TEXT NOT NULL,
    versao INTEGER NOT NULL DEFAULT 1,
    ordem INTEGER NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    aplicada_em TIMESTAMPTZ NOT NULL,
    duracao_ms BIGINT,
    versao_aplicativo INTEGER NOT NULL,
    manifesto_versao INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_schema_migrations PRIMARY KEY (id),
    CONSTRAINT uq_schema_migrations__migration_id UNIQUE (migration_id),
    CONSTRAINT ck_schema_migrations__migration_id_preenchido CHECK (pg_catalog.btrim(migration_id) <> ''),
    CONSTRAINT ck_schema_migrations__modulo_preenchido CHECK (pg_catalog.btrim(modulo) <> ''),
    CONSTRAINT ck_schema_migrations__versao_positivo CHECK (versao > 0),
    CONSTRAINT ck_schema_migrations__ordem_positivo CHECK (ordem > 0),
    CONSTRAINT ck_schema_migrations__manifesto_versao_positivo CHECK (manifesto_versao > 0)
);

CREATE TABLE public.schema_migration_execucoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    migration_id TEXT NOT NULL,
    tentativa INTEGER NOT NULL,
    situacao TEXT NOT NULL,
    iniciada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concluida_em TIMESTAMPTZ,
    duracao_ms BIGINT,
    checksum_sha256 VARCHAR(64) NOT NULL,
    erro_codigo TEXT,
    erro_sanitizado TEXT,
    request_id UUID NOT NULL,
    host_identificador TEXT,
    processo_id INTEGER,
    versao_aplicativo INTEGER NOT NULL,
    CONSTRAINT pk_schema_migration_exec PRIMARY KEY (id),
    CONSTRAINT uq_schema_migration_exec__migration_id_tentativa UNIQUE (migration_id, tentativa),
    CONSTRAINT ck_schema_migration_exec__migration_id_preenchido CHECK (pg_catalog.btrim(migration_id) <> ''),
    CONSTRAINT ck_schema_migration_exec__tentativa_positivo CHECK (tentativa >= 0),
    CONSTRAINT ck_schema_migration_exec__situacao_preenchido CHECK (pg_catalog.btrim(situacao) <> '')
);

CREATE INDEX ix_schema_migration_exec__migration_id_iniciada_em
    ON public.schema_migration_execucoes (migration_id, iniciada_em);

CREATE INDEX ix_schema_migration_exec__request_id
    ON public.schema_migration_execucoes (request_id);
