-- M0010: catalogo conforme baseline H2C.3E

CREATE TABLE unidades_medida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    simbolo TEXT,
    casas_decimais INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    protegido BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE catalogo_grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE catalogo_subgrupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grupo_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE catalogo_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subgrupo_id BIGINT NOT NULL,
    unidade_padrao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    tipo TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE catalogo_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entidade_tipo TEXT NOT NULL,
    grupo_id BIGINT,
    subgrupo_id BIGINT,
    produto_servico_id BIGINT,
    alias TEXT NOT NULL,
    alias_normalizado TEXT NOT NULL,
    origem TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE catalogo_substituicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_origem_id BIGINT NOT NULL,
    item_destino_id BIGINT NOT NULL,
    motivo TEXT,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE catalogo_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entidade_tipo TEXT NOT NULL,
    grupo_id BIGINT,
    subgrupo_id BIGINT,
    produto_servico_id BIGINT,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL
);

ALTER TABLE unidades_medida
    ADD CONSTRAINT pk_unidades_medida PRIMARY KEY (id);

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT pk_catalogo_grupos PRIMARY KEY (id);

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT pk_catalogo_subgrupos PRIMARY KEY (id);

ALTER TABLE catalogo_itens
    ADD CONSTRAINT pk_catalogo_itens PRIMARY KEY (id);

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT pk_catalogo_aliases PRIMARY KEY (id);

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT pk_catalogo_substituicoes PRIMARY KEY (id);

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT pk_catalogo_eventos PRIMARY KEY (id);

ALTER TABLE unidades_medida
    ADD CONSTRAINT uq_unidades_medida__codigo UNIQUE (codigo);

ALTER TABLE unidades_medida
    ADD CONSTRAINT uq_unidades_medida__nome_normalizado UNIQUE (nome_normalizado);

ALTER TABLE unidades_medida
    ADD CONSTRAINT uq_unidades_medida__simbolo UNIQUE (simbolo);

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT uq_catalogo_grupos__codigo UNIQUE (codigo);

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT uq_catalogo_grupos__nome_normalizado UNIQUE (nome_normalizado);

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT uq_catalogo_subgrupos__codigo UNIQUE (codigo);

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT uq_catalogo_subgrupos__grupo_id_nome_normalizado UNIQUE (grupo_id, nome_normalizado);

ALTER TABLE catalogo_itens
    ADD CONSTRAINT uq_catalogo_itens__codigo UNIQUE (codigo);

ALTER TABLE catalogo_itens
    ADD CONSTRAINT uq_catalogo_itens__subgrupo_id_nome_normalizado UNIQUE (subgrupo_id, nome_normalizado);

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT uq_catalogo_aliases__alias_normalizado UNIQUE (alias_normalizado);

CREATE UNIQUE INDEX uq_catalogo_substituicoes__item_origem_id
    ON catalogo_substituicoes (item_origem_id)
    WHERE estado = 'ATIVA' AND fim_data IS NULL;

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__casas_decimais_positivo CHECK (casas_decimais BETWEEN 0 AND 8);

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE unidades_medida
    ADD CONSTRAINT ck_unidades_medida__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__ordem_positivo CHECK (ordem > 0);

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT ck_catalogo_grupos__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__ordem_positivo CHECK (ordem > 0);

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT ck_catalogo_subgrupos__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE catalogo_itens
    ADD CONSTRAINT ck_catalogo_itens__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__entidade_tipo_preenchido CHECK (btrim(entidade_tipo) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__alias_preenchido CHECK (btrim(alias) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__alias_normalizado_preenchido CHECK (btrim(alias_normalizado) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT ck_catalogo_substituicoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT ck_catalogo_substituicoes__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT ck_catalogo_substituicoes__estado CHECK (estado IN ('ATIVA', 'ENCERRADA', 'INATIVA'));

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT ck_catalogo_substituicoes__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT ck_catalogo_eventos__entidade_tipo_preenchido CHECK (btrim(entidade_tipo) <> '');

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT ck_catalogo_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT ck_catalogo_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT ck_catalogo_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT ck_catalogo_aliases__regra_266 CHECK (num_nonnulls(grupo_id,subgrupo_id,produto_servico_id)=1 AND ((entidade_tipo='GRUPO' AND grupo_id IS NOT NULL) OR (entidade_tipo='SUBGRUPO' AND subgrupo_id IS NOT NULL) OR (entidade_tipo='PRODUTO_SERVICO' AND produto_servico_id IS NOT NULL)));

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT ck_catalogo_eventos__regra_267 CHECK (num_nonnulls(grupo_id,subgrupo_id,produto_servico_id)=1 AND ((entidade_tipo='GRUPO' AND grupo_id IS NOT NULL) OR (entidade_tipo='SUBGRUPO' AND subgrupo_id IS NOT NULL) OR (entidade_tipo='PRODUTO_SERVICO' AND produto_servico_id IS NOT NULL)));

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT fk_catalogo_aliases__grupo_id FOREIGN KEY (grupo_id)
    REFERENCES catalogo_grupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT fk_catalogo_aliases__produto_servico_id FOREIGN KEY (produto_servico_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_aliases
    ADD CONSTRAINT fk_catalogo_aliases__subgrupo_id FOREIGN KEY (subgrupo_id)
    REFERENCES catalogo_subgrupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT fk_catalogo_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT fk_catalogo_eventos__grupo_id FOREIGN KEY (grupo_id)
    REFERENCES catalogo_grupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT fk_catalogo_eventos__produto_servico_id FOREIGN KEY (produto_servico_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_eventos
    ADD CONSTRAINT fk_catalogo_eventos__subgrupo_id FOREIGN KEY (subgrupo_id)
    REFERENCES catalogo_subgrupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT fk_catalogo_grupos__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_grupos
    ADD CONSTRAINT fk_catalogo_grupos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_itens
    ADD CONSTRAINT fk_catalogo_itens__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_itens
    ADD CONSTRAINT fk_catalogo_itens__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_itens
    ADD CONSTRAINT fk_catalogo_itens__subgrupo_id FOREIGN KEY (subgrupo_id)
    REFERENCES catalogo_subgrupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_itens
    ADD CONSTRAINT fk_catalogo_itens__unidade_padrao_id FOREIGN KEY (unidade_padrao_id)
    REFERENCES unidades_medida (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT fk_catalogo_subgrupos__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT fk_catalogo_subgrupos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_subgrupos
    ADD CONSTRAINT fk_catalogo_subgrupos__grupo_id FOREIGN KEY (grupo_id)
    REFERENCES catalogo_grupos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT fk_catalogo_substituicoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT fk_catalogo_substituicoes__item_destino_id FOREIGN KEY (item_destino_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE catalogo_substituicoes
    ADD CONSTRAINT fk_catalogo_substituicoes__item_origem_id FOREIGN KEY (item_origem_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_catalogo_aliases__grupo_id
    ON catalogo_aliases (grupo_id);

CREATE INDEX ix_catalogo_aliases__produto_servico_id
    ON catalogo_aliases (produto_servico_id);

CREATE INDEX ix_catalogo_aliases__subgrupo_id
    ON catalogo_aliases (subgrupo_id);

CREATE INDEX ix_catalogo_eventos__criado_por_usr_id
    ON catalogo_eventos (criado_por_usuario_id);

CREATE INDEX ix_catalogo_eventos__grupo_id
    ON catalogo_eventos (grupo_id);

CREATE INDEX ix_catalogo_eventos__produto_servico_id
    ON catalogo_eventos (produto_servico_id);

CREATE INDEX ix_catalogo_eventos__subgrupo_id
    ON catalogo_eventos (subgrupo_id);

CREATE INDEX ix_catalogo_grupos__atualizado_por_usr_id
    ON catalogo_grupos (atualizado_por_usuario_id);

CREATE INDEX ix_catalogo_grupos__criado_por_usr_id
    ON catalogo_grupos (criado_por_usuario_id);

CREATE INDEX ix_catalogo_itens__atualizado_por_usr_id
    ON catalogo_itens (atualizado_por_usuario_id);

CREATE INDEX ix_catalogo_itens__criado_por_usr_id
    ON catalogo_itens (criado_por_usuario_id);

CREATE INDEX ix_catalogo_itens__unidade_padrao_id
    ON catalogo_itens (unidade_padrao_id);

CREATE INDEX ix_catalogo_subgrupos__atualizado_por_usr_id
    ON catalogo_subgrupos (atualizado_por_usuario_id);

CREATE INDEX ix_catalogo_subgrupos__criado_por_usr_id
    ON catalogo_subgrupos (criado_por_usuario_id);

CREATE INDEX ix_catalogo_substituicoes__criado_por_usr_id
    ON catalogo_substituicoes (criado_por_usuario_id);

CREATE INDEX ix_catalogo_substituicoes__item_destino_id
    ON catalogo_substituicoes (item_destino_id);

CREATE INDEX ix_catalogo_itens__subgrupo_id_estado_nome_normalizado
    ON catalogo_itens (subgrupo_id, estado, nome_normalizado);
