-- M0011: financeiro conforme baseline H2C.3E

CREATE TABLE contas_financeiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL,
    instituicao TEXT NOT NULL,
    agencia TEXT NOT NULL,
    conta TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    abertura_data DATE NOT NULL,
    encerramento_data DATE NOT NULL,
    observacoes TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE transacoes_financeiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    associacao_id BIGINT NOT NULL,
    natureza_id BIGINT NOT NULL,
    conta_financeira_id BIGINT NOT NULL,
    associado_id BIGINT,
    data_documento DATE NOT NULL,
    competencia_data DATE NOT NULL,
    numero_documento TEXT,
    contraparte_nome TEXT,
    descricao TEXT,
    valor_total NUMERIC(18,2) NOT NULL,
    estado TEXT NOT NULL DEFAULT 'RASCUNHO',
    origem_transacao_id BIGINT,
    tipo_correcao TEXT,
    fotografia JSONB NOT NULL,
    fotografia_versao INTEGER NOT NULL DEFAULT 1,
    concluida_em TIMESTAMPTZ,
    cancelada_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE transacao_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    catalogo_item_id BIGINT,
    ordem INTEGER NOT NULL,
    descricao_fotografia TEXT NOT NULL,
    unidade_fotografia TEXT NOT NULL,
    quantidade NUMERIC(24,8) NOT NULL,
    valor_unitario NUMERIC(24,8) NOT NULL,
    valor_total NUMERIC(18,2) NOT NULL,
    fotografia JSONB NOT NULL,
    fotografia_versao INTEGER NOT NULL DEFAULT 1,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE transacao_rateios_uvr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    modo TEXT NOT NULL,
    percentual NUMERIC(9,6),
    valor NUMERIC(18,2),
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    concluido_em TIMESTAMPTZ,
    request_id UUID NOT NULL
);

CREATE TABLE transacao_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    valores_fotografia JSONB NOT NULL,
    fotografia_versao INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL,
    resultado TEXT NOT NULL,
    transacao_relacionada_id BIGINT
);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT pk_contas_financeiras PRIMARY KEY (id);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT pk_transacoes_financeiras PRIMARY KEY (id);

ALTER TABLE transacao_itens
    ADD CONSTRAINT pk_transacao_itens PRIMARY KEY (id);

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT pk_transacao_rateios_uvr PRIMARY KEY (id);

ALTER TABLE transacao_eventos
    ADD CONSTRAINT pk_transacao_eventos PRIMARY KEY (id);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT uq_contas_financeiras__assoc_id_codigo UNIQUE (associacao_id, codigo);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT uq_transacoes_financeiras__identificador_publico UNIQUE (identificador_publico);

ALTER TABLE transacao_itens
    ADD CONSTRAINT uq_transacao_itens__transacao_id_ordem UNIQUE (transacao_id, ordem);

CREATE UNIQUE INDEX uq_transacao_rateios_uvr__transacao_id_uvr_id
    ON transacao_rateios_uvr (transacao_id, uvr_id)
    WHERE estado = 'ATIVO';

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__instituicao_preenchido CHECK (btrim(instituicao) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__agencia_preenchido CHECK (btrim(agencia) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__conta_preenchido CHECK (btrim(conta) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__observacoes_preenchido CHECK (btrim(observacoes) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__estado CHECK (estado IN ('ATIVA', 'INATIVA', 'ENCERRADA'));

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__estado CHECK (estado IN ('RASCUNHO', 'CONCLUIDA', 'CANCELADA', 'ESTORNADA'));

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__ordem_positivo CHECK (ordem > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__descricao_fotografia_preenchido CHECK (btrim(descricao_fotografia) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__unidade_fotografia_preenchido CHECK (btrim(unidade_fotografia) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__modo_preenchido CHECK (btrim(modo) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__regra_269 CHECK ((modo='PERCENTUAL' AND percentual BETWEEN 0.000000 AND 100.000000 AND valor IS NULL) OR (modo='VALOR' AND valor BETWEEN 0.00 AND 9999999999999999.99 AND percentual IS NULL));

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__regra_270 CHECK (valor_total BETWEEN 0.00 AND 9999999999999999.99);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__transacao_relacionada_id FOREIGN KEY (transacao_relacionada_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__catalogo_item_id FOREIGN KEY (catalogo_item_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__conta_financeira_id FOREIGN KEY (conta_financeira_id)
    REFERENCES contas_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__natureza_id FOREIGN KEY (natureza_id)
    REFERENCES naturezas_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__origem_transacao_id FOREIGN KEY (origem_transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_contas_financeiras__atualizado_por_usr_id
    ON contas_financeiras (atualizado_por_usuario_id);

CREATE INDEX ix_contas_financeiras__criado_por_usr_id
    ON contas_financeiras (criado_por_usuario_id);

CREATE INDEX ix_transacao_eventos__criado_por_usr_id
    ON transacao_eventos (criado_por_usuario_id);

CREATE INDEX ix_transacao_eventos__transacao_id
    ON transacao_eventos (transacao_id);

CREATE INDEX ix_transacao_eventos__transacao_relacionada_id
    ON transacao_eventos (transacao_relacionada_id);

CREATE INDEX ix_transacao_itens__atualizado_por_usr_id
    ON transacao_itens (atualizado_por_usuario_id);

CREATE INDEX ix_transacao_itens__catalogo_item_id
    ON transacao_itens (catalogo_item_id);

CREATE INDEX ix_transacao_itens__criado_por_usr_id
    ON transacao_itens (criado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__atualizado_por_usr_id
    ON transacao_rateios_uvr (atualizado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__criado_por_usr_id
    ON transacao_rateios_uvr (criado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__uvr_id
    ON transacao_rateios_uvr (uvr_id);

CREATE INDEX ix_transacoes_financeiras__assoc_id
    ON transacoes_financeiras (associacao_id);

CREATE INDEX ix_transacoes_financeiras__associado_id
    ON transacoes_financeiras (associado_id);

CREATE INDEX ix_transacoes_financeiras__atualizado_por_usr_id
    ON transacoes_financeiras (atualizado_por_usuario_id);

CREATE INDEX ix_transacoes_financeiras__conta_financeira_id
    ON transacoes_financeiras (conta_financeira_id);

CREATE INDEX ix_transacoes_financeiras__criado_por_usr_id
    ON transacoes_financeiras (criado_por_usuario_id);

CREATE INDEX ix_transacoes_financeiras__natureza_id
    ON transacoes_financeiras (natureza_id);

CREATE INDEX ix_transacoes_financeiras__origem_transacao_id
    ON transacoes_financeiras (origem_transacao_id);

CREATE INDEX ix_transacoes_financeiras__assoc_id_competencia_data_estado
    ON transacoes_financeiras (associacao_id, competencia_data, estado);
