-- M0012: patrimonio conforme baseline H2C.3E

CREATE TABLE patrimonios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    associacao_responsavel_id BIGINT NOT NULL,
    codigo_patrimonio TEXT NOT NULL,
    descricao TEXT,
    tipo_bem TEXT NOT NULL,
    categoria TEXT NOT NULL,
    marca TEXT,
    modelo TEXT,
    ano_fabricacao INTEGER,
    situacao_propriedade TEXT NOT NULL,
    entidade_proprietaria TEXT,
    condicao TEXT NOT NULL,
    estado_administrativo TEXT NOT NULL,
    combustivel TEXT,
    capacidade NUMERIC(24,8),
    unidade_capacidade TEXT,
    controle_por TEXT NOT NULL,
    medidor_inicial NUMERIC(24,8),
    permite_abastecimento BOOLEAN NOT NULL DEFAULT FALSE,
    permite_manutencao BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE patrimonio_identificadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    valor_original TEXT NOT NULL,
    valor_normalizado TEXT NOT NULL,
    fabricante TEXT NOT NULL,
    classe TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE patrimonio_vinculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    uvr_id BIGINT,
    natureza TEXT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    compartilhado BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    local_instalacao TEXT,
    setor_uso TEXT,
    responsavel_nome_fotografia TEXT,
    operador_nome_fotografia TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    motivo TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE patrimonio_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    condicao_anterior TEXT,
    condicao_nova TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL
);

CREATE TABLE patrimonio_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    categoria TEXT NOT NULL,
    finalidade TEXT NOT NULL,
    ordem INTEGER NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE patrimonio_bloqueios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    motivo TEXT,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL
);

ALTER TABLE patrimonios
    ADD CONSTRAINT pk_patrimonios PRIMARY KEY (id);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT pk_patr_identificadores PRIMARY KEY (id);

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT pk_patr_vinculos PRIMARY KEY (id);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT pk_patr_eventos PRIMARY KEY (id);

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT pk_patr_documentos PRIMARY KEY (id);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT pk_patr_bloqueios PRIMARY KEY (id);

ALTER TABLE patrimonios
    ADD CONSTRAINT uq_patrimonios__identificador_publico UNIQUE (identificador_publico);

CREATE UNIQUE INDEX uq_patrimonios__codigo_patrimonio
    ON patrimonios (codigo_patrimonio)
    WHERE codigo_patrimonio IS NOT NULL AND BTRIM(codigo_patrimonio) <> '';

CREATE UNIQUE INDEX uq_patr_identificadores__tipo_valor_normalizado
    ON patrimonio_identificadores (tipo, valor_normalizado)
    WHERE estado = 'ATIVO';

CREATE UNIQUE INDEX uq_patr_vinculos__patr_id
    ON patrimonio_vinculos (patrimonio_id)
    WHERE principal = TRUE AND estado = 'ATIVO' AND fim_em IS NULL;

CREATE UNIQUE INDEX uq_patr_documentos__patr_id_documento_id_categoria
    ON patrimonio_documentos (patrimonio_id, documento_id, categoria)
    WHERE estado = 'ATIVO' AND fim_em IS NULL;

CREATE UNIQUE INDEX uq_patr_bloqueios__patr_id_tipo
    ON patrimonio_bloqueios (patrimonio_id, tipo)
    WHERE estado = 'ATIVO' AND fim_em IS NULL;

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__codigo_patr_preenchido CHECK (btrim(codigo_patrimonio) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__tipo_bem_preenchido CHECK (btrim(tipo_bem) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__situacao_propriedade_preenchido CHECK (btrim(situacao_propriedade) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__condicao_preenchido CHECK (btrim(condicao) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__estado_administrativo_preenchido CHECK (btrim(estado_administrativo) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__controle_por_preenchido CHECK (btrim(controle_por) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__valor_original_preenchido CHECK (btrim(valor_original) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__valor_normalizado_preenchido CHECK (btrim(valor_normalizado) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__fabricante_preenchido CHECK (btrim(fabricante) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__classe_preenchido CHECK (btrim(classe) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__natureza_preenchido CHECK (btrim(natureza) <> '');

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__finalidade_preenchido CHECK (btrim(finalidade) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__ordem_positivo CHECK (ordem > 0);

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__regra_271 CHECK ((ano_fabricacao IS NULL OR ano_fabricacao BETWEEN 1900 AND 9999) AND (capacidade IS NULL OR capacidade BETWEEN 0 AND 9999999999999999.99999999) AND (medidor_inicial IS NULL OR medidor_inicial BETWEEN 0 AND 9999999999999999.99999999));

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__documento_id FOREIGN KEY (documento_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT fk_patr_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT fk_patr_eventos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT fk_patr_identificadores__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT fk_patr_identificadores__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__assoc_responsavel_id FOREIGN KEY (associacao_responsavel_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_patr_bloqueios__atualizado_por_usr_id
    ON patrimonio_bloqueios (atualizado_por_usuario_id);

CREATE INDEX ix_patr_bloqueios__criado_por_usr_id
    ON patrimonio_bloqueios (criado_por_usuario_id);

CREATE INDEX ix_patr_documentos__criado_por_usr_id
    ON patrimonio_documentos (criado_por_usuario_id);

CREATE INDEX ix_patr_documentos__documento_id
    ON patrimonio_documentos (documento_id);

CREATE INDEX ix_patr_eventos__criado_por_usr_id
    ON patrimonio_eventos (criado_por_usuario_id);

CREATE INDEX ix_patr_eventos__patr_id
    ON patrimonio_eventos (patrimonio_id);

CREATE INDEX ix_patr_identificadores__criado_por_usr_id
    ON patrimonio_identificadores (criado_por_usuario_id);

CREATE INDEX ix_patr_identificadores__patr_id
    ON patrimonio_identificadores (patrimonio_id);

CREATE INDEX ix_patr_vinculos__assoc_id
    ON patrimonio_vinculos (associacao_id);

CREATE INDEX ix_patr_vinculos__criado_por_usr_id
    ON patrimonio_vinculos (criado_por_usuario_id);

CREATE INDEX ix_patr_vinculos__uvr_id
    ON patrimonio_vinculos (uvr_id);

CREATE INDEX ix_patrimonios__assoc_responsavel_id
    ON patrimonios (associacao_responsavel_id);

CREATE INDEX ix_patrimonios__atualizado_por_usr_id
    ON patrimonios (atualizado_por_usuario_id);

CREATE INDEX ix_patrimonios__criado_por_usr_id
    ON patrimonios (criado_por_usuario_id);

CREATE INDEX ix_patrimonios__assoc_responsavel_id_estado_administrativo
    ON patrimonios (associacao_responsavel_id, estado_administrativo);
