-- M0013: solicitacoes conforme baseline H2C.3E

CREATE TABLE solicitacoes_alteracao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    tipo TEXT NOT NULL,
    modulo TEXT NOT NULL,
    objeto_tipo_logico TEXT NOT NULL,
    objeto_identificador_logico TEXT,
    solicitante_usuario_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'RASCUNHO',
    risco TEXT NOT NULL,
    versao_esperada INTEGER NOT NULL,
    fotografia_original JSONB,
    fotografia_proposta JSONB,
    fotografia_aprovada JSONB,
    fotografia_aplicada JSONB,
    formato_versao INTEGER NOT NULL DEFAULT 1,
    justificativa TEXT,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enviada_em TIMESTAMPTZ,
    concluida_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_por_usuario_id INTEGER,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL,
    associacao_contexto_id BIGINT
);

CREATE TABLE solicitacao_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    justificativa TEXT,
    resultado TEXT NOT NULL,
    metadados JSONB,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE solicitacao_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    mensagem TEXT NOT NULL,
    visibilidade TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    editado_em TIMESTAMPTZ,
    editado_por_usuario_id INTEGER,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL,
    removido_em TIMESTAMPTZ
);

CREATE TABLE solicitacao_aprovacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    etapa TEXT NOT NULL,
    decisao TEXT NOT NULL,
    aprovador_usuario_id INTEGER NOT NULL,
    justificativa TEXT,
    risco_observado TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id UUID NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    revogada_em TIMESTAMPTZ,
    revogada_por_usuario_id INTEGER,
    motivo_revogacao TEXT
);

CREATE TABLE solicitacao_aplicacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    tentativa INTEGER NOT NULL,
    aplicador_usuario_id INTEGER NOT NULL,
    iniciada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concluida_em TIMESTAMPTZ,
    versao_observada INTEGER NOT NULL,
    versao_resultante INTEGER,
    resultado TEXT NOT NULL,
    erro_codigo TEXT,
    erro_sanitizado TEXT,
    idempotencia_chave UUID NOT NULL,
    request_id UUID NOT NULL,
    fotografia_resultado JSONB,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE solicitacao_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    categoria TEXT NOT NULL,
    visibilidade TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE solicitacao_associados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    associado_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE solicitacao_associacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE solicitacao_uvrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE solicitacao_catalogo_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    catalogo_item_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE solicitacao_transacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    transacao_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE solicitacao_patrimonios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitacao_id BIGINT NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT pk_solicitacoes_alteracao PRIMARY KEY (id);

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT pk_sol_alt_eventos PRIMARY KEY (id);

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT pk_sol_alt_mensagens PRIMARY KEY (id);

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT pk_sol_alt_aprovacoes PRIMARY KEY (id);

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT pk_sol_alt_aplicacoes PRIMARY KEY (id);

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT pk_sol_alt_documentos PRIMARY KEY (id);

ALTER TABLE solicitacao_associados
    ADD CONSTRAINT pk_sol_alt_associados PRIMARY KEY (id);

ALTER TABLE solicitacao_associacoes
    ADD CONSTRAINT pk_sol_alt_associacoes PRIMARY KEY (id);

ALTER TABLE solicitacao_uvrs
    ADD CONSTRAINT pk_sol_alt_uvrs PRIMARY KEY (id);

ALTER TABLE solicitacao_catalogo_itens
    ADD CONSTRAINT pk_sol_alt_catalogo_itens PRIMARY KEY (id);

ALTER TABLE solicitacao_transacoes
    ADD CONSTRAINT pk_sol_alt_transacoes PRIMARY KEY (id);

ALTER TABLE solicitacao_patrimonios
    ADD CONSTRAINT pk_sol_alt_patrimonios PRIMARY KEY (id);

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT uq_solicitacoes_alteracao__identificador_publico UNIQUE (identificador_publico);

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT uq_sol_alt_aplicacoes__idempotencia_chave UNIQUE (idempotencia_chave);

CREATE UNIQUE INDEX uq_sol_alt_documentos__sol_alt_id_documento_id
    ON solicitacao_documentos (solicitacao_id, documento_id)
    WHERE estado = 'ATIVA';

ALTER TABLE solicitacao_associados
    ADD CONSTRAINT uq_sol_alt_associados__sol_alt_id_associado_id UNIQUE (solicitacao_id, associado_id);

ALTER TABLE solicitacao_associacoes
    ADD CONSTRAINT uq_sol_alt_associacoes__sol_alt_id_assoc_id UNIQUE (solicitacao_id, associacao_id);

ALTER TABLE solicitacao_uvrs
    ADD CONSTRAINT uq_sol_alt_uvrs__sol_alt_id_uvr_id UNIQUE (solicitacao_id, uvr_id);

ALTER TABLE solicitacao_catalogo_itens
    ADD CONSTRAINT uq_sol_alt_catalogo_itens__sol_alt_id_catalogo_item_id UNIQUE (solicitacao_id, catalogo_item_id);

ALTER TABLE solicitacao_transacoes
    ADD CONSTRAINT uq_sol_alt_transacoes__sol_alt_id_transacao_id UNIQUE (solicitacao_id, transacao_id);

ALTER TABLE solicitacao_patrimonios
    ADD CONSTRAINT uq_sol_alt_patrimonios__sol_alt_id_patr_id UNIQUE (solicitacao_id, patrimonio_id);

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__modulo_preenchido CHECK (btrim(modulo) <> '');

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__objeto_tipo_logico_preenchido CHECK (btrim(objeto_tipo_logico) <> '');

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__risco_preenchido CHECK (btrim(risco) <> '');

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__formato_versao_positivo CHECK (formato_versao > 0);

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT ck_solicitacoes_alteracao__estado CHECK (estado IN ('RASCUNHO', 'ENVIADA', 'EM_ANALISE', 'APROVADA', 'REJEITADA', 'APLICADA', 'FALHA', 'CANCELADA'));

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT ck_sol_alt_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT ck_sol_alt_eventos__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT ck_sol_alt_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT ck_sol_alt_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT ck_sol_alt_mensagens__mensagem_preenchido CHECK (btrim(mensagem) <> '');

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT ck_sol_alt_mensagens__visibilidade_preenchido CHECK (btrim(visibilidade) <> '');

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT ck_sol_alt_mensagens__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT ck_sol_alt_mensagens__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT ck_sol_alt_mensagens__estado CHECK (estado IN ('ATIVA', 'REVOGADA', 'REMOVIDA'));

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT ck_sol_alt_aprovacoes__etapa_preenchido CHECK (btrim(etapa) <> '');

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT ck_sol_alt_aprovacoes__decisao_preenchido CHECK (btrim(decisao) <> '');

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT ck_sol_alt_aprovacoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT ck_sol_alt_aprovacoes__estado CHECK (estado IN ('ATIVA', 'REVOGADA', 'REMOVIDA'));

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT ck_sol_alt_aplicacoes__tentativa_positivo CHECK (tentativa >= 0);

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT ck_sol_alt_aplicacoes__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT ck_sol_alt_aplicacoes__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT ck_sol_alt_documentos__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT ck_sol_alt_documentos__visibilidade_preenchido CHECK (btrim(visibilidade) <> '');

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT ck_sol_alt_documentos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT ck_sol_alt_documentos__estado CHECK (estado IN ('ATIVA', 'REVOGADA', 'REMOVIDA'));

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT fk_sol_alt_aplicacoes__aplicador_usr_id FOREIGN KEY (aplicador_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_aplicacoes
    ADD CONSTRAINT fk_sol_alt_aplicacoes__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT fk_sol_alt_aprovacoes__aprovador_usr_id FOREIGN KEY (aprovador_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT fk_sol_alt_aprovacoes__revogada_por_usr_id FOREIGN KEY (revogada_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_aprovacoes
    ADD CONSTRAINT fk_sol_alt_aprovacoes__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associacoes
    ADD CONSTRAINT fk_sol_alt_associacoes__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associacoes
    ADD CONSTRAINT fk_sol_alt_associacoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associacoes
    ADD CONSTRAINT fk_sol_alt_associacoes__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associados
    ADD CONSTRAINT fk_sol_alt_associados__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associados
    ADD CONSTRAINT fk_sol_alt_associados__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_associados
    ADD CONSTRAINT fk_sol_alt_associados__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_catalogo_itens
    ADD CONSTRAINT fk_sol_alt_catalogo_itens__catalogo_item_id FOREIGN KEY (catalogo_item_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_catalogo_itens
    ADD CONSTRAINT fk_sol_alt_catalogo_itens__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_catalogo_itens
    ADD CONSTRAINT fk_sol_alt_catalogo_itens__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT fk_sol_alt_documentos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT fk_sol_alt_documentos__documento_id FOREIGN KEY (documento_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_documentos
    ADD CONSTRAINT fk_sol_alt_documentos__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT fk_sol_alt_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_eventos
    ADD CONSTRAINT fk_sol_alt_eventos__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT fk_sol_alt_mensagens__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT fk_sol_alt_mensagens__editado_por_usr_id FOREIGN KEY (editado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_mensagens
    ADD CONSTRAINT fk_sol_alt_mensagens__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_patrimonios
    ADD CONSTRAINT fk_sol_alt_patrimonios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_patrimonios
    ADD CONSTRAINT fk_sol_alt_patrimonios__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_patrimonios
    ADD CONSTRAINT fk_sol_alt_patrimonios__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_transacoes
    ADD CONSTRAINT fk_sol_alt_transacoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_transacoes
    ADD CONSTRAINT fk_sol_alt_transacoes__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_transacoes
    ADD CONSTRAINT fk_sol_alt_transacoes__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_uvrs
    ADD CONSTRAINT fk_sol_alt_uvrs__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_uvrs
    ADD CONSTRAINT fk_sol_alt_uvrs__sol_alt_id FOREIGN KEY (solicitacao_id)
    REFERENCES solicitacoes_alteracao (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacao_uvrs
    ADD CONSTRAINT fk_sol_alt_uvrs__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT fk_solicitacoes_alteracao__assoc_contexto_id FOREIGN KEY (associacao_contexto_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT fk_solicitacoes_alteracao__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE solicitacoes_alteracao
    ADD CONSTRAINT fk_solicitacoes_alteracao__solicitante_usr_id FOREIGN KEY (solicitante_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_sol_alt_aplicacoes__aplicador_usr_id
    ON solicitacao_aplicacoes (aplicador_usuario_id);

CREATE INDEX ix_sol_alt_aplicacoes__sol_alt_id
    ON solicitacao_aplicacoes (solicitacao_id);

CREATE INDEX ix_sol_alt_aprovacoes__aprovador_usr_id
    ON solicitacao_aprovacoes (aprovador_usuario_id);

CREATE INDEX ix_sol_alt_aprovacoes__revogada_por_usr_id
    ON solicitacao_aprovacoes (revogada_por_usuario_id);

CREATE INDEX ix_sol_alt_aprovacoes__sol_alt_id
    ON solicitacao_aprovacoes (solicitacao_id);

CREATE INDEX ix_sol_alt_associacoes__assoc_id
    ON solicitacao_associacoes (associacao_id);

CREATE INDEX ix_sol_alt_associacoes__criado_por_usr_id
    ON solicitacao_associacoes (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_associados__associado_id
    ON solicitacao_associados (associado_id);

CREATE INDEX ix_sol_alt_associados__criado_por_usr_id
    ON solicitacao_associados (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_catalogo_itens__catalogo_item_id
    ON solicitacao_catalogo_itens (catalogo_item_id);

CREATE INDEX ix_sol_alt_catalogo_itens__criado_por_usr_id
    ON solicitacao_catalogo_itens (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_documentos__criado_por_usr_id
    ON solicitacao_documentos (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_documentos__documento_id
    ON solicitacao_documentos (documento_id);

CREATE INDEX ix_sol_alt_eventos__criado_por_usr_id
    ON solicitacao_eventos (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_eventos__sol_alt_id
    ON solicitacao_eventos (solicitacao_id);

CREATE INDEX ix_sol_alt_mensagens__criado_por_usr_id
    ON solicitacao_mensagens (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_mensagens__editado_por_usr_id
    ON solicitacao_mensagens (editado_por_usuario_id);

CREATE INDEX ix_sol_alt_mensagens__sol_alt_id
    ON solicitacao_mensagens (solicitacao_id);

CREATE INDEX ix_sol_alt_patrimonios__criado_por_usr_id
    ON solicitacao_patrimonios (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_patrimonios__patr_id
    ON solicitacao_patrimonios (patrimonio_id);

CREATE INDEX ix_sol_alt_transacoes__criado_por_usr_id
    ON solicitacao_transacoes (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_transacoes__transacao_id
    ON solicitacao_transacoes (transacao_id);

CREATE INDEX ix_sol_alt_uvrs__criado_por_usr_id
    ON solicitacao_uvrs (criado_por_usuario_id);

CREATE INDEX ix_sol_alt_uvrs__uvr_id
    ON solicitacao_uvrs (uvr_id);

CREATE INDEX ix_solicitacoes_alteracao__assoc_contexto_id
    ON solicitacoes_alteracao (associacao_contexto_id);

CREATE INDEX ix_solicitacoes_alteracao__atualizado_por_usr_id
    ON solicitacoes_alteracao (atualizado_por_usuario_id);

CREATE INDEX ix_solicitacoes_alteracao__solicitante_usr_id
    ON solicitacoes_alteracao (solicitante_usuario_id);

CREATE INDEX ix_solicitacoes_alteracao__estado_risco_criada_em
    ON solicitacoes_alteracao (estado, risco, criada_em);

CREATE INDEX ix_solicitacoes_alteracao__objeto_tipo_logico_objeto_d7a1161f
    ON solicitacoes_alteracao (objeto_tipo_logico, objeto_identificador_logico);
