-- R0001: subconjunto aditivo seguro para reconciliar o schema legado.
-- Fonte normativa: M0002_tipos.sql, comprovadamente ausente por inteiro.
-- SAFE_SUBSET_BEGIN: M0002

-- M0002: tipos conforme baseline H2C.3E

CREATE TABLE auth_modulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    protegido BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE auth_acoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    protegido BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE naturezas_financeiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    protegido BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

ALTER TABLE auth_modulos
    ADD CONSTRAINT pk_auth_modulos PRIMARY KEY (id);

ALTER TABLE auth_acoes
    ADD CONSTRAINT pk_auth_acoes PRIMARY KEY (id);

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT pk_naturezas_financeiras PRIMARY KEY (id);

ALTER TABLE auth_modulos
    ADD CONSTRAINT uq_auth_modulos__codigo UNIQUE (codigo);

ALTER TABLE auth_acoes
    ADD CONSTRAINT uq_auth_acoes__codigo UNIQUE (codigo);

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT uq_naturezas_financeiras__codigo UNIQUE (codigo);

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT uq_naturezas_financeiras__nome_normalizado UNIQUE (nome_normalizado);

ALTER TABLE auth_modulos
    ADD CONSTRAINT ck_auth_modulos__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE auth_modulos
    ADD CONSTRAINT ck_auth_modulos__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE auth_modulos
    ADD CONSTRAINT ck_auth_modulos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE auth_modulos
    ADD CONSTRAINT ck_auth_modulos__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE auth_modulos
    ADD CONSTRAINT ck_auth_modulos__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE auth_acoes
    ADD CONSTRAINT ck_auth_acoes__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE auth_acoes
    ADD CONSTRAINT ck_auth_acoes__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE auth_acoes
    ADD CONSTRAINT ck_auth_acoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE auth_acoes
    ADD CONSTRAINT ck_auth_acoes__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE auth_acoes
    ADD CONSTRAINT ck_auth_acoes__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE naturezas_financeiras
    ADD CONSTRAINT ck_naturezas_financeiras__estado CHECK (estado IN ('ATIVO', 'INATIVO'));
