-- R0004 agrupada: reconcilia exclusivamente M0005-M0008 em uma transação.
-- Requer R0001/R0002/R0003 e todos os prechecks P300+ aprovados.

-- SAFE_SUBSET_BEGIN: M0005
-- M0005: auditoria conforme baseline H2C.3E

CREATE TABLE auditoria_tecnica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id UUID NOT NULL,
    modulo TEXT NOT NULL,
    acao TEXT NOT NULL,
    resultado TEXT NOT NULL,
    tipo_ator TEXT NOT NULL,
    usuario_id INTEGER,
    identificador_ator_tecnico TEXT,
    objeto_tipo TEXT,
    objeto_identificador TEXT,
    associacao_id BIGINT,
    uvr_id BIGINT,
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip INET,
    agente_resumido TEXT,
    origem TEXT NOT NULL,
    justificativa TEXT,
    estado_anterior JSONB,
    estado_posterior JSONB,
    metadados JSONB,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    erro_codigo TEXT
);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT pk_auditoria_tecnica PRIMARY KEY (id);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__modulo_preenchido CHECK (btrim(modulo) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__acao_preenchido CHECK (btrim(acao) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__tipo_ator_preenchido CHECK (btrim(tipo_ator) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT ck_auditoria_tecnica__regra_274 CHECK ((estado_anterior IS NULL OR (jsonb_typeof(estado_anterior)='object' AND octet_length(estado_anterior::text)<=65536)) AND (estado_posterior IS NULL OR (jsonb_typeof(estado_posterior)='object' AND octet_length(estado_posterior::text)<=65536)) AND (metadados IS NULL OR (jsonb_typeof(metadados)='object' AND octet_length(metadados::text)<=65536)));

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__usr_id FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_auditoria_tecnica__assoc_id
    ON auditoria_tecnica (associacao_id);

CREATE INDEX ix_auditoria_tecnica__usr_id
    ON auditoria_tecnica (usuario_id);

CREATE INDEX ix_auditoria_tecnica__uvr_id
    ON auditoria_tecnica (uvr_id);

CREATE INDEX ix_auditoria_tecnica__request_id
    ON auditoria_tecnica (request_id);

CREATE INDEX ix_auditoria_tecnica__objeto_tipo_objeto_identificad_b1794c8b
    ON auditoria_tecnica (objeto_tipo, objeto_identificador, ocorrido_em);

CREATE INDEX ix_auditoria_tecnica__tipo_ator_usr_id_ocorrido_em
    ON auditoria_tecnica (tipo_ator, usuario_id, ocorrido_em);


-- SAFE_SUBSET_BEGIN: M0006
-- M0006: organizacoes conforme baseline H2C.3E

CREATE TABLE associacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'EM_IMPLANTACAO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    inativado_em TIMESTAMPTZ
);

CREATE TABLE associacao_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    alias TEXT NOT NULL,
    alias_normalizado TEXT NOT NULL,
    origem TEXT NOT NULL,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE associacao_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE uvrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    nome_normalizado TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'EM_IMPLANTACAO',
    inicio_data DATE NOT NULL,
    fim_data DATE,
    responsavel_usuario_id INTEGER,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    inativado_em TIMESTAMPTZ
);

CREATE TABLE uvr_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uvr_id BIGINT NOT NULL,
    alias TEXT NOT NULL,
    alias_normalizado TEXT NOT NULL,
    origem TEXT NOT NULL,
    inicio_data DATE NOT NULL,
    fim_data DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE uvr_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uvr_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1
);

ALTER TABLE associacoes
    ADD CONSTRAINT pk_associacoes PRIMARY KEY (id);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT pk_assoc_aliases PRIMARY KEY (id);

ALTER TABLE associacao_eventos
    ADD CONSTRAINT pk_assoc_eventos PRIMARY KEY (id);

ALTER TABLE uvrs
    ADD CONSTRAINT pk_uvrs PRIMARY KEY (id);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT pk_uvr_aliases PRIMARY KEY (id);

ALTER TABLE uvr_eventos
    ADD CONSTRAINT pk_uvr_eventos PRIMARY KEY (id);

ALTER TABLE associacoes
    ADD CONSTRAINT uq_associacoes__codigo UNIQUE (codigo);

ALTER TABLE associacoes
    ADD CONSTRAINT uq_associacoes__nome_normalizado UNIQUE (nome_normalizado);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT uq_assoc_aliases__alias_normalizado UNIQUE (alias_normalizado);

ALTER TABLE uvrs
    ADD CONSTRAINT uq_uvrs__codigo UNIQUE (codigo);

ALTER TABLE uvrs
    ADD CONSTRAINT uq_uvrs__assoc_id_nome_normalizado UNIQUE (associacao_id, nome_normalizado);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT uq_uvr_aliases__alias_normalizado UNIQUE (alias_normalizado);

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__estado CHECK (estado IN ('EM_IMPLANTACAO', 'ATIVA', 'INATIVA'));

ALTER TABLE associacoes
    ADD CONSTRAINT ck_associacoes__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__alias_preenchido CHECK (btrim(alias) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__alias_normalizado_preenchido CHECK (btrim(alias_normalizado) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE associacao_aliases
    ADD CONSTRAINT ck_assoc_aliases__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE associacao_eventos
    ADD CONSTRAINT ck_assoc_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE associacao_eventos
    ADD CONSTRAINT ck_assoc_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__nome_normalizado_preenchido CHECK (btrim(nome_normalizado) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__estado CHECK (estado IN ('EM_IMPLANTACAO', 'ATIVA', 'INATIVA'));

ALTER TABLE uvrs
    ADD CONSTRAINT ck_uvrs__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__alias_preenchido CHECK (btrim(alias) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__alias_normalizado_preenchido CHECK (btrim(alias_normalizado) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE uvr_aliases
    ADD CONSTRAINT ck_uvr_aliases__periodo CHECK (fim_data IS NULL OR fim_data >= inicio_data);

ALTER TABLE uvr_eventos
    ADD CONSTRAINT ck_uvr_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE uvr_eventos
    ADD CONSTRAINT ck_uvr_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE associacao_aliases
    ADD CONSTRAINT fk_assoc_aliases__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_aliases
    ADD CONSTRAINT fk_assoc_aliases__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_eventos
    ADD CONSTRAINT fk_assoc_eventos__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacao_eventos
    ADD CONSTRAINT fk_assoc_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacoes
    ADD CONSTRAINT fk_associacoes__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE associacoes
    ADD CONSTRAINT fk_associacoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auditoria_tecnica
    ADD CONSTRAINT fk_auditoria_tecnica__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_aliases
    ADD CONSTRAINT fk_uvr_aliases__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_aliases
    ADD CONSTRAINT fk_uvr_aliases__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_eventos
    ADD CONSTRAINT fk_uvr_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvr_eventos
    ADD CONSTRAINT fk_uvr_eventos__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE uvrs
    ADD CONSTRAINT fk_uvrs__responsavel_usr_id FOREIGN KEY (responsavel_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_assoc_aliases__assoc_id
    ON associacao_aliases (associacao_id);

CREATE INDEX ix_assoc_aliases__criado_por_usr_id
    ON associacao_aliases (criado_por_usuario_id);

CREATE INDEX ix_assoc_eventos__assoc_id
    ON associacao_eventos (associacao_id);

CREATE INDEX ix_assoc_eventos__criado_por_usr_id
    ON associacao_eventos (criado_por_usuario_id);

CREATE INDEX ix_associacoes__atualizado_por_usr_id
    ON associacoes (atualizado_por_usuario_id);

CREATE INDEX ix_associacoes__criado_por_usr_id
    ON associacoes (criado_por_usuario_id);

CREATE INDEX ix_uvr_aliases__criado_por_usr_id
    ON uvr_aliases (criado_por_usuario_id);

CREATE INDEX ix_uvr_aliases__uvr_id
    ON uvr_aliases (uvr_id);

CREATE INDEX ix_uvr_eventos__criado_por_usr_id
    ON uvr_eventos (criado_por_usuario_id);

CREATE INDEX ix_uvr_eventos__uvr_id
    ON uvr_eventos (uvr_id);

CREATE INDEX ix_uvrs__atualizado_por_usr_id
    ON uvrs (atualizado_por_usuario_id);

CREATE INDEX ix_uvrs__criado_por_usr_id
    ON uvrs (criado_por_usuario_id);

CREATE INDEX ix_uvrs__responsavel_usr_id
    ON uvrs (responsavel_usuario_id);

CREATE INDEX ix_associacoes__estado_nome_normalizado
    ON associacoes (estado, nome_normalizado);

CREATE INDEX ix_uvrs__assoc_id_estado_nome_normalizado
    ON uvrs (associacao_id, estado, nome_normalizado);


-- SAFE_SUBSET_BEGIN: M0007
-- M0007: escopos conforme baseline H2C.3E

CREATE TABLE auth_escopos_globais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE auth_escopos_associacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE auth_escopos_uvr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_perfil_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT pk_auth_escopos_globais PRIMARY KEY (id);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT pk_auth_escopos_associacao PRIMARY KEY (id);

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT pk_auth_escopos_uvr PRIMARY KEY (id);

CREATE UNIQUE INDEX uq_auth_escopos_globais__usr_perfil_id
    ON auth_escopos_globais (usuario_perfil_id)
    WHERE fim_em IS NULL;

CREATE UNIQUE INDEX uq_auth_escopos_assoc__usr_perfil_id_assoc_id
    ON auth_escopos_associacao (usuario_perfil_id, associacao_id)
    WHERE fim_em IS NULL;

CREATE UNIQUE INDEX uq_auth_escopos_uvr__usr_perfil_id_uvr_id
    ON auth_escopos_uvr (usuario_perfil_id, uvr_id)
    WHERE fim_em IS NULL;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT ck_auth_escopos_globais__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT ck_auth_escopos_assoc__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT ck_auth_escopos_uvr__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_associacao
    ADD CONSTRAINT fk_auth_escopos_assoc__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT fk_auth_escopos_globais__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_globais
    ADD CONSTRAINT fk_auth_escopos_globais__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__usr_perfil_id FOREIGN KEY (usuario_perfil_id)
    REFERENCES auth_usuario_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_escopos_uvr
    ADD CONSTRAINT fk_auth_escopos_uvr__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_auth_escopos_assoc__assoc_id
    ON auth_escopos_associacao (associacao_id);

CREATE INDEX ix_auth_escopos_assoc__criado_por_usr_id
    ON auth_escopos_associacao (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_globais__criado_por_usr_id
    ON auth_escopos_globais (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_uvr__criado_por_usr_id
    ON auth_escopos_uvr (criado_por_usuario_id);

CREATE INDEX ix_auth_escopos_uvr__uvr_id
    ON auth_escopos_uvr (uvr_id);


-- SAFE_SUBSET_BEGIN: M0008
-- M0008: documentos conforme baseline H2C.3E

CREATE TABLE documentos_privados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    provedor TEXT NOT NULL,
    chave_provedor TEXT NOT NULL,
    nome_original TEXT NOT NULL,
    nome_seguro TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    extensao TEXT NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    versao INTEGER NOT NULL DEFAULT 1,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    privacidade TEXT NOT NULL,
    substituido_por_id BIGINT,
    retencao_ate DATE,
    excluido_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

ALTER TABLE documentos_privados
    ADD CONSTRAINT pk_documentos_privados PRIMARY KEY (id);

ALTER TABLE documentos_privados
    ADD CONSTRAINT uq_documentos_privados__identificador_publico UNIQUE (identificador_publico);

ALTER TABLE documentos_privados
    ADD CONSTRAINT uq_documentos_privados__chave_provedor UNIQUE (chave_provedor);

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__provedor_preenchido CHECK (btrim(provedor) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__chave_provedor_preenchido CHECK (btrim(chave_provedor) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__nome_original_preenchido CHECK (btrim(nome_original) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__nome_seguro_preenchido CHECK (btrim(nome_seguro) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__mime_type_preenchido CHECK (btrim(mime_type) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__extensao_preenchido CHECK (btrim(extensao) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__versao_positivo CHECK (versao > 0);

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__privacidade_preenchido CHECK (btrim(privacidade) <> '');

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__estado CHECK (estado IN ('ATIVO', 'SUBSTITUIDO', 'INATIVO', 'EXCLUSAO_PENDENTE'));

ALTER TABLE documentos_privados
    ADD CONSTRAINT ck_documentos_privados__regra_268 CHECK (sha256 ~ '^[0-9a-f]{64}$' AND tamanho_bytes >= 0 AND versao > 0);

ALTER TABLE documentos_privados
    ADD CONSTRAINT fk_documentos_privados__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE documentos_privados
    ADD CONSTRAINT fk_documentos_privados__substituido_por_id FOREIGN KEY (substituido_por_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_documentos_privados__criado_por_usr_id
    ON documentos_privados (criado_por_usuario_id);

CREATE INDEX ix_documentos_privados__substituido_por_id
    ON documentos_privados (substituido_por_id);

CREATE INDEX ix_documentos_privados__estado_retencao_ate
    ON documentos_privados (estado, retencao_ate);

CREATE INDEX ix_documentos_privados__sha256
    ON documentos_privados (sha256);
