-- R0006 agrupada: reconcilia M0011-M0012 após R0001-R0005.
-- Execução futura: uma única transação; rollback integral em qualquer falha.
-- Não executa M0013, não altera fc_* nem objetos EXTRA_LEGADO.
-- H2D13-CLASS-C: column|transacoes_financeiras|id PATH=public.transacoes_financeiras.id
-- H2D13-CLASS-C: sequence|transacoes_financeiras_id_seq PATH=public.transacoes_financeiras_id_seq
-- EXTRA_LEGADO PRESERVADO POR DECISAO NORMATIVA.

-- M0011
CREATE TABLE contas_financeiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associacao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL,
    instituicao TEXT,
    agencia TEXT,
    conta TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    abertura_data DATE,
    encerramento_data DATE,
    observacoes TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

-- A tabela transacoes_financeiras e data_documento ja existem no legado.
ALTER TABLE public.transacoes_financeiras
    ALTER COLUMN numero_documento TYPE TEXT;

ALTER TABLE public.transacoes_financeiras
    ADD COLUMN identificador_publico UUID,
    ADD COLUMN associacao_id BIGINT,
    ADD COLUMN natureza_id BIGINT,
    ADD COLUMN conta_financeira_id BIGINT,
    ADD COLUMN associado_id BIGINT,
    ADD COLUMN competencia_data DATE,
    ADD COLUMN contraparte_nome TEXT,
    ADD COLUMN descricao TEXT,
    ADD COLUMN valor_total NUMERIC(18,2),
    ADD COLUMN estado TEXT NOT NULL DEFAULT 'RASCUNHO',
    ADD COLUMN origem_transacao_id BIGINT,
    ADD COLUMN tipo_correcao TEXT,
    ADD COLUMN fotografia JSONB,
    ADD COLUMN fotografia_versao INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN concluida_em TIMESTAMPTZ,
    ADD COLUMN cancelada_em TIMESTAMPTZ,
    ADD COLUMN criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN criado_por_usuario_id INTEGER,
    ADD COLUMN atualizado_por_usuario_id INTEGER,
    ADD COLUMN versao_registro INTEGER NOT NULL DEFAULT 1;

CREATE TABLE transacao_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    catalogo_item_id BIGINT,
    ordem INTEGER NOT NULL,
    descricao_fotografia TEXT NOT NULL,
    unidade_fotografia TEXT NOT NULL,
    quantidade NUMERIC(24,8) NOT NULL,
    valor_unitario NUMERIC(24,8) NOT NULL,
    valor_total NUMERIC(18,2) NOT NULL,
    fotografia JSONB NOT NULL,
    fotografia_versao INTEGER NOT NULL DEFAULT 1,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE transacao_rateios_uvr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    uvr_id BIGINT NOT NULL,
    modo TEXT NOT NULL,
    percentual NUMERIC(9,6),
    valor NUMERIC(18,2),
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    concluido_em TIMESTAMPTZ,
    request_id UUID NOT NULL
);

CREATE TABLE transacao_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transacao_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    motivo TEXT,
    valores_fotografia JSONB NOT NULL,
    fotografia_versao INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL,
    resultado TEXT NOT NULL,
    transacao_relacionada_id BIGINT
);


-- M0011: seeds estruturais RECEITA/DESPESA.
DO $r0006_seeds$
DECLARE
    v_codigo TEXT;
    v_total INTEGER;
    v_seguro INTEGER;
BEGIN
    FOREACH v_codigo IN ARRAY ARRAY['RECEITA', 'DESPESA'] LOOP
        SELECT count(*), count(*) FILTER (WHERE codigo = v_codigo
                                          AND nome = v_codigo
                                          AND nome_normalizado = lower(v_codigo)
                                          AND estado = 'ATIVO')
          INTO v_total, v_seguro
          FROM public.naturezas_financeiras
         WHERE codigo = v_codigo OR nome_normalizado = lower(v_codigo);
        IF v_total = 0 THEN
            INSERT INTO public.naturezas_financeiras (codigo, nome, nome_normalizado)
            VALUES (v_codigo, v_codigo, lower(v_codigo));
        ELSIF v_total <> 1 OR v_seguro <> 1 THEN
            RAISE EXCEPTION 'R0006/NATUREZA: colisao incompatível para %', v_codigo;
        END IF;
    END LOOP;
END
$r0006_seeds$;

-- M0011: materializa/reutiliza associacoes pela identidade legada token<->UVR.
DO $r0006_associacoes$
DECLARE
    v_usuario_id INTEGER;
    v_invalidas INTEGER;
BEGIN
    SELECT id
      INTO STRICT v_usuario_id
      FROM public.usuarios
     WHERE username = 'migracao_dados_legados'
       AND username_normalizado = 'migracao_dados_legados'
       AND estado = 'BLOQUEADO'
       AND ativo = FALSE;

    WITH legacy_pairs AS (
        SELECT lower(btrim(tf.associacao)) AS token_normalizado,
               btrim(tf.associacao) AS sigla_historica,
               lower(btrim(tf.uvr)) AS uvr_legada,
               count(*) AS quantidade_transacoes
          FROM public.transacoes_financeiras AS tf
         GROUP BY 1, 2, 3
    ), legacy_identity AS (
        SELECT token_normalizado,
               count(*) AS pares_legacy,
               count(DISTINCT sigla_historica) AS siglas_historicas,
               count(DISTINCT uvr_legada) AS uvrs_legacy
          FROM legacy_pairs
         GROUP BY token_normalizado
    ), uvr_identity AS (
        SELECT uvr_legada, count(DISTINCT token_normalizado) AS tokens_por_uvr
          FROM legacy_pairs
         GROUP BY uvr_legada
    ), canonical_candidates AS (
        SELECT li.token_normalizado, a.id AS associacao_id
          FROM legacy_identity AS li
          JOIN public.associacoes AS a ON lower(btrim(a.codigo)) = li.token_normalizado
        UNION
        SELECT li.token_normalizado, a.id AS associacao_id
          FROM legacy_identity AS li
          JOIN public.associacoes AS a ON a.nome_normalizado = li.token_normalizado
        UNION
        SELECT li.token_normalizado, aa.associacao_id
          FROM legacy_identity AS li
          JOIN public.associacao_aliases AS aa ON aa.alias_normalizado = li.token_normalizado
    ), candidate_counts AS (
        SELECT token_normalizado, count(*) AS candidate_count
          FROM canonical_candidates GROUP BY token_normalizado
    ), divergent_codes AS (
        SELECT DISTINCT li.token_normalizado, a.id AS associacao_id
          FROM legacy_identity AS li
          JOIN public.associacoes AS a
            ON a.nome_normalizado = li.token_normalizado
            OR EXISTS (
                SELECT 1 FROM public.associacao_aliases AS aa
                 WHERE aa.associacao_id = a.id
                   AND aa.alias_normalizado = li.token_normalizado
            )
         WHERE a.codigo IS NOT NULL AND btrim(a.codigo) <> ''
           AND lower(btrim(a.codigo)) <> li.token_normalizado
    )
    SELECT count(*)
      INTO v_invalidas
      FROM legacy_identity AS li
      LEFT JOIN legacy_pairs AS lp
        ON lp.token_normalizado = li.token_normalizado AND li.pares_legacy = 1
      LEFT JOIN uvr_identity AS ui ON ui.uvr_legada = lp.uvr_legada
      LEFT JOIN candidate_counts AS cc ON cc.token_normalizado = li.token_normalizado
     WHERE li.token_normalizado IS NULL OR li.token_normalizado = ''
        OR li.siglas_historicas <> 1 OR li.uvrs_legacy <> 1
        OR COALESCE(ui.tokens_por_uvr, 0) <> 1
        OR COALESCE(cc.candidate_count, 0) > 1
        OR EXISTS (SELECT 1 FROM divergent_codes AS dc
                    WHERE dc.token_normalizado = li.token_normalizado);

    IF v_invalidas <> 0 THEN
        RAISE EXCEPTION 'R0006/ASSOCIACAO: identidade legacy ou candidato canonico ambiguo/incompativel';
    END IF;

    WITH legacy_pairs AS (
        SELECT lower(btrim(tf.associacao)) AS token_normalizado,
               btrim(tf.associacao) AS sigla_historica,
               lower(btrim(tf.uvr)) AS uvr_legada,
               count(*) AS quantidade_transacoes
          FROM public.transacoes_financeiras AS tf
         GROUP BY 1, 2, 3
    ), legacy_identity AS (
        SELECT token_normalizado, count(*) AS pares_legacy,
               count(DISTINCT sigla_historica) AS siglas_historicas,
               count(DISTINCT uvr_legada) AS uvrs_legacy
          FROM legacy_pairs GROUP BY token_normalizado
    ), canonical_candidates AS (
        SELECT li.token_normalizado, a.id AS associacao_id
          FROM legacy_identity AS li
          JOIN public.associacoes AS a ON lower(btrim(a.codigo)) = li.token_normalizado
        UNION
        SELECT li.token_normalizado, a.id AS associacao_id
          FROM legacy_identity AS li
          JOIN public.associacoes AS a ON a.nome_normalizado = li.token_normalizado
        UNION
        SELECT li.token_normalizado, aa.associacao_id
          FROM legacy_identity AS li
          JOIN public.associacao_aliases AS aa ON aa.alias_normalizado = li.token_normalizado
    ), candidate_counts AS (
        SELECT token_normalizado, count(*) AS candidate_count
          FROM canonical_candidates GROUP BY token_normalizado
    )
    INSERT INTO public.associacoes (
        codigo, nome, nome_normalizado, descricao, estado, inicio_data,
        criado_por_usuario_id, atualizado_por_usuario_id
    )
    SELECT lp.sigla_historica, lp.sigla_historica, lp.token_normalizado,
           NULL, 'EM_IMPLANTACAO', CURRENT_DATE, v_usuario_id, v_usuario_id
      FROM legacy_pairs AS lp
      JOIN legacy_identity AS li
        ON li.token_normalizado = lp.token_normalizado
       AND li.pares_legacy = 1 AND li.siglas_historicas = 1 AND li.uvrs_legacy = 1
      LEFT JOIN candidate_counts AS cc ON cc.token_normalizado = lp.token_normalizado
     WHERE COALESCE(cc.candidate_count, 0) = 0;

    WITH legacy_tokens AS (
        SELECT DISTINCT lower(btrim(tf.associacao)) AS token_normalizado
          FROM public.transacoes_financeiras AS tf
    ), canonical_candidates AS (
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON lower(btrim(a.codigo)) = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON a.nome_normalizado = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, aa.associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacao_aliases AS aa ON aa.alias_normalizado = lt.token_normalizado
    ), candidate_counts AS (
        SELECT token_normalizado, count(*) AS candidate_count
          FROM canonical_candidates GROUP BY token_normalizado
    )
    SELECT count(*)
      INTO v_invalidas
      FROM legacy_tokens AS lt
      LEFT JOIN candidate_counts AS cc ON cc.token_normalizado = lt.token_normalizado
     WHERE COALESCE(cc.candidate_count, 0) <> 1;

    IF v_invalidas <> 0 THEN
        RAISE EXCEPTION 'R0006/ASSOCIACAO: cardinalidade canonica final diferente de 1';
    END IF;
END
$r0006_associacoes$;

-- M0011: uma conta tecnica inativa por associacao efetivamente necessaria.
DO $r0006_contas$
DECLARE
    v_usuario_id INTEGER;
BEGIN
    SELECT id INTO STRICT v_usuario_id
      FROM public.usuarios
     WHERE username = 'migracao_dados_legados'
       AND username_normalizado = 'migracao_dados_legados'
       AND estado = 'BLOQUEADO'
       AND ativo = FALSE;

    WITH legacy_tokens AS (
        SELECT DISTINCT lower(btrim(tf.associacao)) AS token_normalizado
          FROM public.transacoes_financeiras AS tf
    ), canonical_candidates AS (
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON lower(btrim(a.codigo)) = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON a.nome_normalizado = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, aa.associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacao_aliases AS aa ON aa.alias_normalizado = lt.token_normalizado
    ), candidate_counts AS (
        SELECT token_normalizado, count(*) AS candidate_count
          FROM canonical_candidates GROUP BY token_normalizado
    ), resolucao AS (
        SELECT cc.token_normalizado, cc.associacao_id
          FROM canonical_candidates AS cc
          JOIN candidate_counts AS n USING (token_normalizado)
         WHERE n.candidate_count = 1
    ), necessarias AS (
        SELECT DISTINCT associacao_id FROM resolucao
    )
    INSERT INTO public.contas_financeiras (
        associacao_id, codigo, nome, tipo, instituicao, agencia, conta,
        estado, abertura_data, encerramento_data, observacoes,
        criado_por_usuario_id, atualizado_por_usuario_id
    )
    SELECT n.associacao_id,
           'MIGRACAO_LEGADO',
           'Migração de dados legados',
           'MIGRACAO_LEGADO',
           NULL, NULL, NULL,
           'INATIVA',
           NULL, NULL,
           'Registro técnico criado exclusivamente para vinculação de transações financeiras legadas sem identificação inequívoca da conta financeira histórica.',
           v_usuario_id, v_usuario_id
      FROM necessarias AS n
     WHERE NOT EXISTS (
         SELECT 1 FROM public.contas_financeiras AS cf
          WHERE cf.associacao_id = n.associacao_id
            AND cf.codigo = 'MIGRACAO_LEGADO'
     );
END
$r0006_contas$;

-- M0011: backfill estritamente limitado as nove colunas novas autorizadas.
WITH resolucao AS (
    WITH legacy_tokens AS (
        SELECT DISTINCT lower(btrim(tf.associacao)) AS token_normalizado
          FROM public.transacoes_financeiras AS tf
    ), canonical_candidates AS (
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON lower(btrim(a.codigo)) = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, a.id AS associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacoes AS a ON a.nome_normalizado = lt.token_normalizado
        UNION
        SELECT lt.token_normalizado, aa.associacao_id
          FROM legacy_tokens AS lt
          JOIN public.associacao_aliases AS aa ON aa.alias_normalizado = lt.token_normalizado
    ), candidate_counts AS (
        SELECT token_normalizado, count(*) AS candidate_count
          FROM canonical_candidates GROUP BY token_normalizado
    )
    SELECT tf.id AS transacao_id, cc.associacao_id
      FROM public.transacoes_financeiras AS tf
      JOIN canonical_candidates AS cc
        ON cc.token_normalizado = lower(btrim(tf.associacao))
      JOIN candidate_counts AS n USING (token_normalizado)
     WHERE n.candidate_count = 1
), usuario AS (
    SELECT id
      FROM public.usuarios
     WHERE username = 'migracao_dados_legados'
       AND username_normalizado = 'migracao_dados_legados'
       AND estado = 'BLOQUEADO'
       AND ativo = FALSE
)
UPDATE public.transacoes_financeiras AS tf
   SET identificador_publico = pg_catalog.gen_random_uuid(),
       associacao_id = r.associacao_id,
       natureza_id = nf.id,
       conta_financeira_id = cf.id,
       competencia_data = tf.data_documento,
       valor_total = tf.valor_total_documento,
       fotografia = jsonb_build_object(
           'versao', 1,
           'origem', 'MIGRACAO_LEGADO',
           'legado', jsonb_build_object(
               'id', tf.id,
               'numero_documento', tf.numero_documento,
               'data_documento', tf.data_documento,
               'tipo_transacao', tf.tipo_transacao,
               'valor_total_documento', tf.valor_total_documento,
               'associacao', tf.associacao
           )
       ),
       criado_por_usuario_id = u.id,
       atualizado_por_usuario_id = u.id
  FROM resolucao AS r
  JOIN public.contas_financeiras AS cf
    ON cf.associacao_id = r.associacao_id
   AND cf.codigo = 'MIGRACAO_LEGADO'
   AND cf.tipo = 'MIGRACAO_LEGADO'
  JOIN public.naturezas_financeiras AS nf
    ON nf.codigo IN ('RECEITA', 'DESPESA')
  CROSS JOIN usuario AS u
 WHERE r.transacao_id = tf.id
   AND nf.codigo = upper(public.unaccent(btrim(tf.tipo_transacao)));

ALTER TABLE public.transacoes_financeiras
    ALTER COLUMN identificador_publico SET NOT NULL,
    ALTER COLUMN associacao_id SET NOT NULL,
    ALTER COLUMN natureza_id SET NOT NULL,
    ALTER COLUMN conta_financeira_id SET NOT NULL,
    ALTER COLUMN competencia_data SET NOT NULL,
    ALTER COLUMN valor_total SET NOT NULL,
    ALTER COLUMN fotografia SET NOT NULL,
    ALTER COLUMN criado_por_usuario_id SET NOT NULL,
    ALTER COLUMN atualizado_por_usuario_id SET NOT NULL;

ALTER TABLE contas_financeiras
    ADD CONSTRAINT pk_contas_financeiras PRIMARY KEY (id);

-- H2D13-PRESERVE_EQUIVALENT: a PK legada existente permanece intacta; nao se cria segunda PK.

ALTER TABLE transacao_itens
    ADD CONSTRAINT pk_transacao_itens PRIMARY KEY (id);

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT pk_transacao_rateios_uvr PRIMARY KEY (id);

ALTER TABLE transacao_eventos
    ADD CONSTRAINT pk_transacao_eventos PRIMARY KEY (id);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT uq_contas_financeiras__assoc_id_codigo UNIQUE (associacao_id, codigo);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT uq_transacoes_financeiras__identificador_publico UNIQUE (identificador_publico);

ALTER TABLE transacao_itens
    ADD CONSTRAINT uq_transacao_itens__transacao_id_ordem UNIQUE (transacao_id, ordem);

CREATE UNIQUE INDEX uq_transacao_rateios_uvr__transacao_id_uvr_id
    ON transacao_rateios_uvr (transacao_id, uvr_id)
    WHERE estado = 'ATIVO';

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__instituicao_preenchido CHECK ((tipo = 'MIGRACAO_LEGADO' AND instituicao IS NULL) OR (tipo <> 'MIGRACAO_LEGADO' AND instituicao IS NOT NULL AND btrim(instituicao) <> ''));

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__agencia_preenchido CHECK ((tipo = 'MIGRACAO_LEGADO' AND agencia IS NULL) OR (tipo <> 'MIGRACAO_LEGADO' AND agencia IS NOT NULL AND btrim(agencia) <> ''));

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__conta_preenchido CHECK ((tipo = 'MIGRACAO_LEGADO' AND conta IS NULL) OR (tipo <> 'MIGRACAO_LEGADO' AND conta IS NOT NULL AND btrim(conta) <> ''));

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__observacoes_preenchido CHECK (btrim(observacoes) <> '');

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__datas_modalidade CHECK (
        (tipo = 'MIGRACAO_LEGADO' AND abertura_data IS NULL AND encerramento_data IS NULL)
        OR
        (tipo <> 'MIGRACAO_LEGADO' AND abertura_data IS NOT NULL AND encerramento_data IS NOT NULL)
    );

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT ck_contas_financeiras__estado CHECK (estado IN ('ATIVA', 'INATIVA', 'ENCERRADA'));

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__estado CHECK (estado IN ('RASCUNHO', 'CONCLUIDA', 'CANCELADA', 'ESTORNADA'));

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__ordem_positivo CHECK (ordem > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__descricao_fotografia_preenchido CHECK (btrim(descricao_fotografia) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__unidade_fotografia_preenchido CHECK (btrim(unidade_fotografia) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacao_itens
    ADD CONSTRAINT ck_transacao_itens__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__modo_preenchido CHECK (btrim(modo) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__fotografia_versao_positivo CHECK (fotografia_versao > 0);

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE transacao_eventos
    ADD CONSTRAINT ck_transacao_eventos__resultado_preenchido CHECK (btrim(resultado) <> '');

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT ck_transacao_rateios_uvr__regra_269 CHECK ((modo='PERCENTUAL' AND percentual BETWEEN 0.000000 AND 100.000000 AND valor IS NULL) OR (modo='VALOR' AND valor BETWEEN 0.00 AND 9999999999999999.99 AND percentual IS NULL));

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT ck_transacoes_financeiras__regra_270 CHECK (valor_total BETWEEN 0.00 AND 9999999999999999.99);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_eventos
    ADD CONSTRAINT fk_transacao_eventos__transacao_relacionada_id FOREIGN KEY (transacao_relacionada_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__catalogo_item_id FOREIGN KEY (catalogo_item_id)
    REFERENCES catalogo_itens (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_itens
    ADD CONSTRAINT fk_transacao_itens__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__transacao_id FOREIGN KEY (transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacao_rateios_uvr
    ADD CONSTRAINT fk_transacao_rateios_uvr__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__associado_id FOREIGN KEY (associado_id)
    REFERENCES associados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__conta_financeira_id FOREIGN KEY (conta_financeira_id)
    REFERENCES contas_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__natureza_id FOREIGN KEY (natureza_id)
    REFERENCES naturezas_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE transacoes_financeiras
    ADD CONSTRAINT fk_transacoes_financeiras__origem_transacao_id FOREIGN KEY (origem_transacao_id)
    REFERENCES transacoes_financeiras (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_contas_financeiras__atualizado_por_usr_id
    ON contas_financeiras (atualizado_por_usuario_id);

CREATE INDEX ix_contas_financeiras__criado_por_usr_id
    ON contas_financeiras (criado_por_usuario_id);

CREATE INDEX ix_transacao_eventos__criado_por_usr_id
    ON transacao_eventos (criado_por_usuario_id);

CREATE INDEX ix_transacao_eventos__transacao_id
    ON transacao_eventos (transacao_id);

CREATE INDEX ix_transacao_eventos__transacao_relacionada_id
    ON transacao_eventos (transacao_relacionada_id);

CREATE INDEX ix_transacao_itens__atualizado_por_usr_id
    ON transacao_itens (atualizado_por_usuario_id);

CREATE INDEX ix_transacao_itens__catalogo_item_id
    ON transacao_itens (catalogo_item_id);

CREATE INDEX ix_transacao_itens__criado_por_usr_id
    ON transacao_itens (criado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__atualizado_por_usr_id
    ON transacao_rateios_uvr (atualizado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__criado_por_usr_id
    ON transacao_rateios_uvr (criado_por_usuario_id);

CREATE INDEX ix_transacao_rateios_uvr__uvr_id
    ON transacao_rateios_uvr (uvr_id);

CREATE INDEX ix_transacoes_financeiras__assoc_id
    ON transacoes_financeiras (associacao_id);

CREATE INDEX ix_transacoes_financeiras__associado_id
    ON transacoes_financeiras (associado_id);

CREATE INDEX ix_transacoes_financeiras__atualizado_por_usr_id
    ON transacoes_financeiras (atualizado_por_usuario_id);

CREATE INDEX ix_transacoes_financeiras__conta_financeira_id
    ON transacoes_financeiras (conta_financeira_id);

CREATE INDEX ix_transacoes_financeiras__criado_por_usr_id
    ON transacoes_financeiras (criado_por_usuario_id);

CREATE INDEX ix_transacoes_financeiras__natureza_id
    ON transacoes_financeiras (natureza_id);

CREATE INDEX ix_transacoes_financeiras__origem_transacao_id
    ON transacoes_financeiras (origem_transacao_id);

CREATE INDEX ix_transacoes_financeiras__assoc_id_competencia_data_estado
    ON transacoes_financeiras (associacao_id, competencia_data, estado);

-- M0012
CREATE TABLE patrimonios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificador_publico UUID NOT NULL,
    associacao_responsavel_id BIGINT NOT NULL,
    codigo_patrimonio TEXT NOT NULL,
    descricao TEXT,
    tipo_bem TEXT NOT NULL,
    categoria TEXT NOT NULL,
    marca TEXT,
    modelo TEXT,
    ano_fabricacao INTEGER,
    situacao_propriedade TEXT NOT NULL,
    entidade_proprietaria TEXT,
    condicao TEXT NOT NULL,
    estado_administrativo TEXT NOT NULL,
    combustivel TEXT,
    capacidade NUMERIC(24,8),
    unidade_capacidade TEXT,
    controle_por TEXT NOT NULL,
    medidor_inicial NUMERIC(24,8),
    permite_abastecimento BOOLEAN NOT NULL DEFAULT FALSE,
    permite_manutencao BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE patrimonio_identificadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    valor_original TEXT NOT NULL,
    valor_normalizado TEXT NOT NULL,
    fabricante TEXT NOT NULL,
    classe TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE patrimonio_vinculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    associacao_id BIGINT NOT NULL,
    uvr_id BIGINT,
    natureza TEXT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    compartilhado BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    local_instalacao TEXT,
    setor_uso TEXT,
    responsavel_nome_fotografia TEXT,
    operador_nome_fotografia TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    motivo TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL
);

CREATE TABLE patrimonio_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo_evento TEXT NOT NULL,
    estado_anterior TEXT,
    estado_novo TEXT,
    condicao_anterior TEXT,
    condicao_nova TEXT,
    motivo TEXT,
    fotografia JSONB NOT NULL,
    versao_formato INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    request_id UUID NOT NULL,
    origem TEXT NOT NULL
);

CREATE TABLE patrimonio_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    categoria TEXT NOT NULL,
    finalidade TEXT NOT NULL,
    ordem INTEGER NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL
);

CREATE TABLE patrimonio_bloqueios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patrimonio_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    motivo TEXT,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL
);

ALTER TABLE patrimonios
    ADD CONSTRAINT pk_patrimonios PRIMARY KEY (id);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT pk_patr_identificadores PRIMARY KEY (id);

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT pk_patr_vinculos PRIMARY KEY (id);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT pk_patr_eventos PRIMARY KEY (id);

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT pk_patr_documentos PRIMARY KEY (id);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT pk_patr_bloqueios PRIMARY KEY (id);

ALTER TABLE patrimonios
    ADD CONSTRAINT uq_patrimonios__identificador_publico UNIQUE (identificador_publico);

CREATE UNIQUE INDEX uq_patrimonios__codigo_patrimonio
    ON patrimonios (codigo_patrimonio)
    WHERE codigo_patrimonio IS NOT NULL AND BTRIM(codigo_patrimonio) <> '';

CREATE UNIQUE INDEX uq_patr_identificadores__tipo_valor_normalizado
    ON patrimonio_identificadores (tipo, valor_normalizado)
    WHERE estado = 'ATIVO';

CREATE UNIQUE INDEX uq_patr_vinculos__patr_id
    ON patrimonio_vinculos (patrimonio_id)
    WHERE principal = TRUE AND estado = 'ATIVO' AND fim_em IS NULL;

CREATE UNIQUE INDEX uq_patr_documentos__patr_id_documento_id_categoria
    ON patrimonio_documentos (patrimonio_id, documento_id, categoria)
    WHERE estado = 'ATIVO' AND fim_em IS NULL;

CREATE UNIQUE INDEX uq_patr_bloqueios__patr_id_tipo
    ON patrimonio_bloqueios (patrimonio_id, tipo)
    WHERE estado = 'ATIVO' AND fim_em IS NULL;

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__codigo_patr_preenchido CHECK (btrim(codigo_patrimonio) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__tipo_bem_preenchido CHECK (btrim(tipo_bem) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__situacao_propriedade_preenchido CHECK (btrim(situacao_propriedade) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__condicao_preenchido CHECK (btrim(condicao) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__estado_administrativo_preenchido CHECK (btrim(estado_administrativo) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__controle_por_preenchido CHECK (btrim(controle_por) <> '');

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__valor_original_preenchido CHECK (btrim(valor_original) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__valor_normalizado_preenchido CHECK (btrim(valor_normalizado) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__fabricante_preenchido CHECK (btrim(fabricante) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__classe_preenchido CHECK (btrim(classe) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT ck_patr_identificadores__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__natureza_preenchido CHECK (btrim(natureza) <> '');

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT ck_patr_vinculos__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__tipo_evento_preenchido CHECK (btrim(tipo_evento) <> '');

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__versao_formato_positivo CHECK (versao_formato > 0);

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT ck_patr_eventos__origem_preenchido CHECK (btrim(origem) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__categoria_preenchido CHECK (btrim(categoria) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__finalidade_preenchido CHECK (btrim(finalidade) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__ordem_positivo CHECK (ordem > 0);

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT ck_patr_documentos__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__tipo_preenchido CHECK (btrim(tipo) <> '');

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__estado CHECK (estado IN ('ATIVO', 'ENCERRADO', 'INATIVO'));

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT ck_patr_bloqueios__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE patrimonios
    ADD CONSTRAINT ck_patrimonios__regra_271 CHECK ((ano_fabricacao IS NULL OR ano_fabricacao BETWEEN 1900 AND 9999) AND (capacidade IS NULL OR capacidade BETWEEN 0 AND 9999999999999999.99999999) AND (medidor_inicial IS NULL OR medidor_inicial BETWEEN 0 AND 9999999999999999.99999999));

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_bloqueios
    ADD CONSTRAINT fk_patr_bloqueios__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__documento_id FOREIGN KEY (documento_id)
    REFERENCES documentos_privados (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_documentos
    ADD CONSTRAINT fk_patr_documentos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT fk_patr_eventos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_eventos
    ADD CONSTRAINT fk_patr_eventos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT fk_patr_identificadores__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_identificadores
    ADD CONSTRAINT fk_patr_identificadores__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__assoc_id FOREIGN KEY (associacao_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__patr_id FOREIGN KEY (patrimonio_id)
    REFERENCES patrimonios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonio_vinculos
    ADD CONSTRAINT fk_patr_vinculos__uvr_id FOREIGN KEY (uvr_id)
    REFERENCES uvrs (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__assoc_responsavel_id FOREIGN KEY (associacao_responsavel_id)
    REFERENCES associacoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE patrimonios
    ADD CONSTRAINT fk_patrimonios__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_patr_bloqueios__atualizado_por_usr_id
    ON patrimonio_bloqueios (atualizado_por_usuario_id);

CREATE INDEX ix_patr_bloqueios__criado_por_usr_id
    ON patrimonio_bloqueios (criado_por_usuario_id);

CREATE INDEX ix_patr_documentos__criado_por_usr_id
    ON patrimonio_documentos (criado_por_usuario_id);

CREATE INDEX ix_patr_documentos__documento_id
    ON patrimonio_documentos (documento_id);

CREATE INDEX ix_patr_eventos__criado_por_usr_id
    ON patrimonio_eventos (criado_por_usuario_id);

CREATE INDEX ix_patr_eventos__patr_id
    ON patrimonio_eventos (patrimonio_id);

CREATE INDEX ix_patr_identificadores__criado_por_usr_id
    ON patrimonio_identificadores (criado_por_usuario_id);

CREATE INDEX ix_patr_identificadores__patr_id
    ON patrimonio_identificadores (patrimonio_id);

CREATE INDEX ix_patr_vinculos__assoc_id
    ON patrimonio_vinculos (associacao_id);

CREATE INDEX ix_patr_vinculos__criado_por_usr_id
    ON patrimonio_vinculos (criado_por_usuario_id);

CREATE INDEX ix_patr_vinculos__uvr_id
    ON patrimonio_vinculos (uvr_id);

CREATE INDEX ix_patrimonios__assoc_responsavel_id
    ON patrimonios (associacao_responsavel_id);

CREATE INDEX ix_patrimonios__atualizado_por_usr_id
    ON patrimonios (atualizado_por_usuario_id);

CREATE INDEX ix_patrimonios__criado_por_usr_id
    ON patrimonios (criado_por_usuario_id);

CREATE INDEX ix_patrimonios__assoc_responsavel_id_estado_administrativo
    ON patrimonios (associacao_responsavel_id, estado_administrativo);
