-- R0003: reconcilia exclusivamente os 99 objetos ausentes de M0004.
-- Requer R0001/M0002, R0002/M0003 e P200-P207 validados.
-- SAFE_SUBSET_BEGIN: M0004
-- M0004: autorizacao conforme baseline H2C.3E

CREATE TABLE auth_permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modulo_id BIGINT NOT NULL,
    acao_id BIGINT NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE auth_perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT,
    estado TEXT NOT NULL DEFAULT 'ATIVO',
    protegido BOOLEAN NOT NULL DEFAULT FALSE,
    escopo_tipo TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    atualizado_por_usuario_id INTEGER NOT NULL,
    versao_registro INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE auth_perfil_permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    perfil_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por_usuario_id INTEGER NOT NULL,
    justificativa TEXT
);

CREATE TABLE auth_usuario_perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id INTEGER NOT NULL,
    perfil_id BIGINT NOT NULL,
    inicio_em TIMESTAMPTZ NOT NULL,
    fim_em TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'ATIVA',
    justificativa TEXT,
    concedido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concedido_por_usuario_id INTEGER NOT NULL,
    revogado_em TIMESTAMPTZ,
    revogado_por_usuario_id INTEGER,
    motivo_revogacao TEXT,
    versao_registro INTEGER NOT NULL DEFAULT 1,
    request_id UUID NOT NULL
);

ALTER TABLE auth_permissoes
    ADD CONSTRAINT pk_auth_permissoes PRIMARY KEY (id);

ALTER TABLE auth_perfis
    ADD CONSTRAINT pk_auth_perfis PRIMARY KEY (id);

ALTER TABLE auth_perfil_permissoes
    ADD CONSTRAINT pk_auth_perfil_permissoes PRIMARY KEY (id);

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT pk_auth_usr_perfis PRIMARY KEY (id);

ALTER TABLE auth_permissoes
    ADD CONSTRAINT uq_auth_permissoes__codigo UNIQUE (codigo);

ALTER TABLE auth_permissoes
    ADD CONSTRAINT uq_auth_permissoes__modulo_id_acao_id UNIQUE (modulo_id, acao_id);

ALTER TABLE auth_perfis
    ADD CONSTRAINT uq_auth_perfis__codigo UNIQUE (codigo);

ALTER TABLE auth_perfil_permissoes
    ADD CONSTRAINT uq_auth_perfil_permissoes__perfil_id_permissao_id UNIQUE (perfil_id, permissao_id);

CREATE UNIQUE INDEX uq_auth_usr_perfis__usr_id_perfil_id
    ON auth_usuario_perfis (usuario_id, perfil_id)
    WHERE estado = 'ATIVA' AND fim_em IS NULL;

ALTER TABLE auth_permissoes
    ADD CONSTRAINT ck_auth_permissoes__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE auth_permissoes
    ADD CONSTRAINT ck_auth_permissoes__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE auth_permissoes
    ADD CONSTRAINT ck_auth_permissoes__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE auth_permissoes
    ADD CONSTRAINT ck_auth_permissoes__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__codigo_preenchido CHECK (btrim(codigo) <> '');

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__nome_preenchido CHECK (btrim(nome) <> '');

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__escopo_tipo_preenchido CHECK (btrim(escopo_tipo) <> '');

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE auth_perfis
    ADD CONSTRAINT ck_auth_perfis__estado CHECK (estado IN ('ATIVO', 'INATIVO'));

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT ck_auth_usr_perfis__estado_preenchido CHECK (btrim(estado) <> '');

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT ck_auth_usr_perfis__versao_registro_positivo CHECK (versao_registro > 0);

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT ck_auth_usr_perfis__estado CHECK (estado IN ('ATIVA', 'REVOGADA', 'EXPIRADA'));

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT ck_auth_usr_perfis__periodo CHECK (fim_em IS NULL OR fim_em >= inicio_em);

ALTER TABLE auth_perfil_permissoes
    ADD CONSTRAINT fk_auth_perfil_permissoes__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_perfil_permissoes
    ADD CONSTRAINT fk_auth_perfil_permissoes__perfil_id FOREIGN KEY (perfil_id)
    REFERENCES auth_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_perfil_permissoes
    ADD CONSTRAINT fk_auth_perfil_permissoes__permissao_id FOREIGN KEY (permissao_id)
    REFERENCES auth_permissoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_perfis
    ADD CONSTRAINT fk_auth_perfis__atualizado_por_usr_id FOREIGN KEY (atualizado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_perfis
    ADD CONSTRAINT fk_auth_perfis__criado_por_usr_id FOREIGN KEY (criado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_permissoes
    ADD CONSTRAINT fk_auth_permissoes__acao_id FOREIGN KEY (acao_id)
    REFERENCES auth_acoes (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_permissoes
    ADD CONSTRAINT fk_auth_permissoes__modulo_id FOREIGN KEY (modulo_id)
    REFERENCES auth_modulos (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT fk_auth_usr_perfis__concedido_por_usr_id FOREIGN KEY (concedido_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT fk_auth_usr_perfis__perfil_id FOREIGN KEY (perfil_id)
    REFERENCES auth_perfis (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT fk_auth_usr_perfis__revogado_por_usr_id FOREIGN KEY (revogado_por_usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE auth_usuario_perfis
    ADD CONSTRAINT fk_auth_usr_perfis__usr_id FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE NO ACTION NOT DEFERRABLE;

CREATE INDEX ix_auth_perfil_permissoes__criado_por_usr_id
    ON auth_perfil_permissoes (criado_por_usuario_id);

CREATE INDEX ix_auth_perfil_permissoes__permissao_id
    ON auth_perfil_permissoes (permissao_id);

CREATE INDEX ix_auth_perfis__atualizado_por_usr_id
    ON auth_perfis (atualizado_por_usuario_id);

CREATE INDEX ix_auth_perfis__criado_por_usr_id
    ON auth_perfis (criado_por_usuario_id);

CREATE INDEX ix_auth_permissoes__acao_id
    ON auth_permissoes (acao_id);

CREATE INDEX ix_auth_usr_perfis__concedido_por_usr_id
    ON auth_usuario_perfis (concedido_por_usuario_id);

CREATE INDEX ix_auth_usr_perfis__perfil_id
    ON auth_usuario_perfis (perfil_id);

CREATE INDEX ix_auth_usr_perfis__revogado_por_usr_id
    ON auth_usuario_perfis (revogado_por_usuario_id);
